SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;


articles;
CREATE TABLE articles (
  id bigint(20) NOT NULL,
  product varchar(255) NOT NULL DEFAULT '',
  fecha date NOT NULL,
  respuestas smallint(6) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------


lp2008_adicionales;
CREATE TABLE lp2008_adicionales (
  ID mediumint(9) NOT NULL,
  TIPO enum('DV','IN') NOT NULL DEFAULT 'DV',
  ADICIONAL varchar(40) NOT NULL,
  PUBLICADOS smallint(6) NOT NULL DEFAULT '0'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='ALMACENA LOS ADICIONALES DE ARTICULOS, VEH E INM';

lp2008_adicxarti;
CREATE TABLE lp2008_adicxarti (
  ARTICULO_ID int(11) NOT NULL,
  ADICIONAL_ID mediumint(9) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='ALMACENA ENLACE ENTRE LOS ADICIONALES Y ARTICULOS';


CREATE TABLE lp2008_anclarpub (
  ARTICULO_ID mediumint(6) NOT NULL,
  CANTIDAD smallint(4) DEFAULT '0' COMMENT 'cantidad de clicks utilizados',
  LIMITE mediumint(9) NOT NULL DEFAULT '1' COMMENT 'limite de clicks limitados'
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='Publicaciones ancladas en su categoria';


CREATE TABLE lp2008_artcoords (
  ARTICULO_ID mediumint(9) NOT NULL,
  LAT varchar(25) NOT NULL,
  LNG varchar(25) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='CONTIENE LAS COORDENADAS DE UN ARTICULO U OFERTA PARA MAPA';

CREATE TABLE lp2008_articulos (
  ID mediumint(9) NOT NULL,
  USUARIO_ID mediumint(9) NOT NULL DEFAULT '0',
  FECHA datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  EXPIRA datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  PUBLICADO enum('M','P') NOT NULL DEFAULT 'P' COMMENT 'M - MOVIL, P - PC',
  TIPO enum('C','V','S','B','A','T','M','E') NOT NULL DEFAULT 'V',
  PLAN enum('P','O','L','T','D','I') NOT NULL DEFAULT 'P' COMMENT 'TIPO DE PLAN DEL USUARIO',
  USUPLAN enum('PB','OP1','OP2','LPE','LP','LP+','TIE','DEA','INM') NOT NULL DEFAULT 'PB',
  PROVINCIA smallint(6) NOT NULL COMMENT 'LISTA POR PROVINCIAS',
  MUNICIPIO smallint(6) NOT NULL,
  LISTA enum('R','L') NOT NULL DEFAULT 'L' COMMENT 'L - NUEVOS, R - RENOVADOS',
  CATEGORIA_ID smallint(6) NOT NULL DEFAULT '1',
  SUBCATEGORIA_ID smallint(6) NOT NULL DEFAULT '1',
  ESTATUS enum('A','R','I','F','T','P','RO','RU','V','PA','RT') NOT NULL DEFAULT 'A' COMMENT 'RO: retira operador, RU: retira usuario, V Marcado vendido, PA-Pendiente aprobacion, RT - retirado temporal',
  CANTIDAD int(11) NOT NULL DEFAULT '1',
  PRECIO decimal(12,2) NOT NULL DEFAULT '0.00',
  ENVIO decimal(9,2) NOT NULL DEFAULT '0.00' COMMENT 'MONTO DE ENVIO',
  BONO enum('S','N') NOT NULL DEFAULT 'N' COMMENT 'MARCA SI EL ARTICULO TIENE BONO O NO',
  BN_FORMA enum('P','V') NOT NULL DEFAULT 'P',
  BN_VALOR decimal(15,2) NOT NULL DEFAULT '0.00',
  BN_HASTA date NOT NULL DEFAULT '0000-00-00',
  FORMAPAGO enum('P','G','T','N') NOT NULL DEFAULT 'N',
  MONEDA enum('R','U','E') NOT NULL DEFAULT 'R',
  ARTICULO varchar(70) NOT NULL DEFAULT '',
  REFERENCIA varchar(50) DEFAULT NULL,
  URLVIDEO varchar(120) NOT NULL DEFAULT '',
  OPCIONAL enum('N','R','FL') NOT NULL DEFAULT 'N',
  RESALTADO enum('N','R','FL') NOT NULL DEFAULT 'N' COMMENT 'RESALTA PUBLICACION',
  OPCHASTA datetime DEFAULT '0000-00-00 00:00:00',
  RESHASTA datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT 'FECHA CADUCA RESALTADO',
  APTABLOQUE enum('S','N') NOT NULL DEFAULT 'S' COMMENT 'APTA PARA BLOQUE VIP, AO, TIV, DEA, INM',
  PUBLICIDAD enum('S','N') NOT NULL DEFAULT 'N' COMMENT 'USADO PARA PUBLICIDAD ADWORDS',
  LINKAPLAN enum('S','N') NOT NULL DEFAULT 'N' COMMENT 'ENVIA PUBLICACION A PLAN O NO',
  FUERAPLAN enum('S','N') NOT NULL DEFAULT 'N' COMMENT 'PUBLICACIONES FUERA DEL PLAN',
  CONDICION enum('1','2','3','4','5') NOT NULL DEFAULT '1',
  FOTOS varchar(150) DEFAULT NULL,
  FOTOEXTERNA enum('S','N') NOT NULL DEFAULT 'N',
  URLFOTOEXT varchar(150) DEFAULT NULL,
  ROTAFOTO enum('N','S') NOT NULL DEFAULT 'N',
  VISITAS smallint(6) NOT NULL DEFAULT '0',
  VISITADO timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  ACUMULADAS smallint(6) NOT NULL DEFAULT '0' COMMENT 'VISITAS ACUMULADAS',
  ELIMINADO datetime DEFAULT NULL COMMENT 'FECHA ELIMINADO POR EL USUARIO',
  MOTIVOELI tinyint(4) DEFAULT NULL COMMENT 'MOTIVO ELIMIANDO POR EL USUARIO',
  IPADDRESS varchar(25) NOT NULL DEFAULT ''
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='ALMACENA LOS ARTICULOS DE USUARIOS REGISTRADOS';



CREATE TABLE lp2008_arttemp (
  ID int(11) NOT NULL,
  ARTICULO varchar(70) NOT NULL,
  PRECIO decimal(12,2) NOT NULL,
  CATEGORIA_ID smallint(6) NOT NULL DEFAULT '1',
  SUBCATEGORIA_ID smallint(6) NOT NULL DEFAULT '1',
  COMPLEMENTO varchar(15) NOT NULL,
  USUARIO_ID varchar(9) DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='ALMACENA PUBLICACIONES TEMPORALES IMPORTADAS DESDE EXCEL';


CREATE TABLE lp2008_autocompleta (
  ID int(11) NOT NULL COMMENT 'ID DEL REGISTRO',
  STR varchar(70) NOT NULL COMMENT 'STR O TITULO',
  CANTIDAD smallint(6) NOT NULL DEFAULT '0' COMMENT 'CANTIDAD  DE OCURRENCIAS'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='CONTIENE VALORES PARA AUTOCOMPLETE';

CREATE TABLE lp2008_braices (
  ARTICULO_ID mediumint(9) NOT NULL DEFAULT '0',
  HABITACIONES varchar(4) NOT NULL DEFAULT '0',
  BANOS varchar(10) NOT NULL DEFAULT '0',
  MCONSTRUIDOS varchar(10) NOT NULL DEFAULT '0',
  MTERRENO varchar(10) NOT NULL DEFAULT '0',
  PARQUEOS varchar(10) NOT NULL DEFAULT '0',
  EDIFICABLE varchar(5) DEFAULT NULL,
  CONSTRUCCION varchar(10) NOT NULL DEFAULT 'N/A',
  ANIO varchar(10) NOT NULL DEFAULT 'N/A',
  USOACTUAL varchar(10) NOT NULL DEFAULT 'N/A',
  PROVINCIA smallint(6) NOT NULL DEFAULT '0',
  SECTOR smallint(6) NOT NULL DEFAULT '0',
  LAT varchar(25) DEFAULT NULL COMMENT 'LATITUD COORD',
  LNG varchar(25) DEFAULT NULL COMMENT 'LONGITUD COORD',
  MAPA enum('S','N') NOT NULL DEFAULT 'S' COMMENT 'PERMITE MOSTRAR MAPA O NO',
  ESTATUS enum('A','I') NOT NULL DEFAULT 'A'
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

lp2008_busquedas;
CREATE TABLE lp2008_busquedas (
  CUANTOS smallint(6) NOT NULL,
  STR varchar(60) NOT NULL,
  TIPO varchar(1) NOT NULL COMMENT 'TIPO DE BUSQUEDA N=NORMAL, U=USUARIO, T=NOMBRE TIENDA '
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='GUARDA LAS BUSQUEDAS MAS POPULARES';

lp2008_buzon;
CREATE TABLE lp2008_buzon (
  ID mediumint(9) NOT NULL,
  PARA mediumint(9) NOT NULL DEFAULT '0',
  DE mediumint(9) NOT NULL DEFAULT '0',
  DEEMAIL varchar(100) NOT NULL COMMENT 'EMAIL EN QUE ENVIA ',
  ARTICULO_ID mediumint(9) NOT NULL DEFAULT '0',
  ASUNTO varchar(70) NOT NULL DEFAULT '',
  FECHA timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  ESTATUS enum('N','L','C','R') NOT NULL DEFAULT 'N',
  ADDRESS varchar(25) CHARACTER SET latin1 NOT NULL COMMENT 'IP ADDRESS',
  SESSION varchar(40) NOT NULL COMMENT 'SESSION ID USUARIO QUE ENVIA',
  MENSAJE text NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='TABLA PARA ALMACENAR MENSAJES ENVIADOS A USUARIOS DE OTROS';

CREATE TABLE lp2008_cambioregistro (
  ID mediumint(9) NOT NULL,
  USUARIO_ID mediumint(9) NOT NULL DEFAULT '0',
  TABLA varchar(20) NOT NULL DEFAULT '',
  CAMPO tinytext CHARACTER SET latin1 NOT NULL,
  VALOR text NOT NULL,
  FECHA timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  IPADDRESS varchar(50) CHARACTER SET latin1 NOT NULL DEFAULT ''
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='REGISTRA LOS CAMBIOS HECHOS A CAMPOS EN USUARIOS Y ARTICULOS';

lp2008_categorias;
CREATE TABLE lp2008_categorias (
  ID smallint(6) NOT NULL DEFAULT '0',
  CATEGORIA varchar(150) NOT NULL DEFAULT '',
  PUBLICADOS mediumint(9) NOT NULL DEFAULT '0'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='TABLA DE CATEGORIAS DE ARITUCLOS';

lp2008_celulares;
CREATE TABLE lp2008_celulares (
  ARTICULO_ID mediumint(9) NOT NULL DEFAULT '0',
  MARCACE varchar(3) NOT NULL DEFAULT '0',
  MODELO varchar(5) NOT NULL DEFAULT '0',
  TECNOLOGIA enum('GSM','CDMA') NOT NULL DEFAULT 'GSM',
  IMEI varchar(20) DEFAULT NULL COMMENT 'CODIGO DEL MOVIL PUBLICADO',
  USARFOTOS enum('S','N') NOT NULL DEFAULT 'N',
  ESTATUS enum('A','I') NOT NULL DEFAULT 'A'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='ALMACENA DATOS CELULARES DE ARTICULOS';

lp2008_cemarca;
CREATE TABLE lp2008_cemarca (
  ID tinyint(4) NOT NULL,
  MARCA varchar(40) NOT NULL DEFAULT '',
  PUBLICADOS smallint(6) NOT NULL DEFAULT '0'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='CONTIENE LA MARCA DE LOS CELULARES';

lp2008_cemodelo;
CREATE TABLE lp2008_cemodelo (
  ID smallint(5) NOT NULL,
  MARCA_ID tinyint(5) NOT NULL DEFAULT '0',
  MODELO varchar(50) NOT NULL DEFAULT '',
  PUBLICADOS smallint(6) NOT NULL DEFAULT '0'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='MODELOS DE CELULARES';

lp2008_comentarticulos;
CREATE TABLE lp2008_comentarticulos (
  ID bigint(20) NOT NULL,
  ARTICULO_ID bigint(20) NOT NULL DEFAULT '0',
  FECHA timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  USUARIO_ID int(11) NOT NULL DEFAULT '0',
  COMENTARIO text NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='COMENTARIO HECHOS A LOS ARTICULOS POR USUARIOS';

CREATE TABLE lp2008_complementos (
  ARTICULO_ID int(11) NOT NULL,
  TIPOCOMP enum('CE','VE','BR') NOT NULL,
  MARCA varchar(4) NOT NULL DEFAULT '0',
  MODELO varchar(4) DEFAULT '0',
  ANIO varchar(4) NOT NULL DEFAULT 'N/A',
  COMBUSTIBLE varchar(5) NOT NULL DEFAULT 'N/A',
  GOMAS varchar(20) DEFAULT NULL COMMENT 'DIAMETRO DE LAS GOMAS 999/99/99',
  AROS varchar(20) DEFAULT NULL COMMENT 'DIAMETRO DE LAS GOMAS 999/99/99',
  PROVINCIA varchar(4) DEFAULT NULL,
  SECTOR varchar(4) DEFAULT NULL,
  HABITACIONES varchar(4) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  BANOS varchar(10) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  PARQUEOS varchar(10) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  MCONSTRUIDOS varchar(10) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  MTERRENO varchar(10) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  LAT varchar(25) DEFAULT NULL COMMENT 'LATITUD COORD',
  LNG varchar(25) DEFAULT NULL COMMENT 'LONGITUD COORD',
  MAPA enum('S','N') DEFAULT 'N' COMMENT 'PERMITE MOSTRAR MAPA O NO',
  ESTATUS enum('A','R','I','F','T','RO','RU','V','PA','RT') NOT NULL DEFAULT 'A'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='CONTIENE INFO ADICIONAL DE CADA PUBLICACION, BR, CE, VEH';


CREATE TABLE lp2008_comusu (
  ID mediumint(9) NOT NULL,
  OPERADOR_ID mediumint(9) NOT NULL,
  USUARIO_ID mediumint(9) NOT NULL DEFAULT '0',
  COMENTARIO text NOT NULL,
  PRIORIDAD enum('A','B') NOT NULL DEFAULT 'B',
  SEGUIMIENTO tinyint(4) NOT NULL DEFAULT '0' COMMENT 'SEGUIMIENTO EN DIAS',
  FECHA datetime NOT NULL DEFAULT '0000-00-00 00:00:00'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='COMENTARIOS ALMACENADOS PARA USUARIOS';

lp2008_cupones;
CREATE TABLE lp2008_cupones (
  CUPON varchar(10) NOT NULL,
  USUARIO_ID mediumint(9) DEFAULT NULL COMMENT 'USUARIO QUE RECIBIO EL CUPON',
  ESTATUS enum('A','I') NOT NULL DEFAULT 'A',
  FECHA datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT 'FECHA EN LA QUE SE USO EL CUPON'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='CONTIENE LOS CUPONES PARA REGISTROS';

CREATE TABLE lp2008_descripcion (
  ARTICULO_ID mediumint(9) NOT NULL DEFAULT '0',
  DESCRIPCION text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='CONTIENE LA DESCRIPCION DE LOS ARTICULOS';


CREATE TABLE lp2008_desctemp (
  ARTICULO_ID varchar(50) NOT NULL DEFAULT '',
  DESCRIPCION text NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='TABLA TEMPORAL PARA LAS DESCRIPCIONES POR LOTE';

lp2008_descuentos;
CREATE TABLE lp2008_descuentos (
  ARTICULO_ID mediumint(9) NOT NULL DEFAULT '0',
  FORMA enum('P','V') NOT NULL DEFAULT 'P',
  VALOR decimal(15,2) NOT NULL DEFAULT '0.00',
  HASTA date NOT NULL DEFAULT '0000-00-00',
  ESTATUS enum('A','I') NOT NULL DEFAULT 'A',
  BONO enum('S','N') NOT NULL DEFAULT 'N' COMMENT 'SI APLICA BONO',
  NOTA enum('1','2','3') NOT NULL DEFAULT '1' COMMENT 'NOTAS PREDETERMINADAS'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='DESCUENTOS APLICADOS A LOS ARTICULOS';

lp2008_dominios;
CREATE TABLE lp2008_dominios (
  DOMINIO varchar(60) NOT NULL DEFAULT '',
  CANTIDAD tinyint(5) NOT NULL DEFAULT '0',
  CORREGIDO varchar(60) NOT NULL DEFAULT ''
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

lp2008_ealternos;
CREATE TABLE lp2008_ealternos (
  USUARIO_ID mediumint(9) NOT NULL DEFAULT '0',
  EMAILS text NOT NULL COMMENT 'EMAILS ALTERNO DE ESTE USUARIO'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='ALMACENA LOS EMAILS ALTERNOS DEL USUARIO';

lp2008_eliart;
CREATE TABLE lp2008_eliart (
  ID mediumint(9) NOT NULL,
  USUARIO_ID mediumint(9) NOT NULL DEFAULT '0',
  CANTIDAD tinyint(4) NOT NULL DEFAULT '0',
  FECHA datetime NOT NULL DEFAULT '0000-00-00 00:00:00'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='REGISTRA LA CANTIDAD DE ARTICULOS ELIMINADOS POR USUARIO';

lp2008_encuestas;
CREATE TABLE lp2008_encuestas (
  ID bigint(20) NOT NULL,
  PREGUNTA varchar(255) NOT NULL DEFAULT '',
  ESTATUS enum('A','I') NOT NULL DEFAULT 'A',
  FECHA datetime NOT NULL,
  HORAS int(11) DEFAULT NULL,
  RESPUESTAS smallint(6) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

lp2008_enlpatr;
CREATE TABLE lp2008_enlpatr (
  ID mediumint(5) NOT NULL COMMENT 'ID que identifica el enlace patrocinado',
  USUARIO_ID mediumint(9) NOT NULL COMMENT 'id del usuario en cuestion',
  TIPO enum('PP','PU','PL') NOT NULL DEFAULT 'PP' COMMENT 'PP - PUBLICACION, PL - PLAN DE USUARIO, PU - PROMOCIONA USUARIO',
  SECCION tinyint(2) NOT NULL COMMENT 'seccion en la que se mostrara el enlace',
  IDSOURCE mediumint(9) NOT NULL COMMENT 'id del recurso en cuestion dependiendo de la seccion: ej: tiendas:id de la tienda',
  TITULO varchar(70) DEFAULT NULL,
  DESCRIPCION varchar(200) NOT NULL COMMENT 'descripcion del enlace',
  FORMA enum('PC','PI') NOT NULL COMMENT 'forma en que se mostrara los enlaces pc:por clicks, pi:por impresion',
  CANTIDAD smallint(4) DEFAULT '0' COMMENT 'cantidad de impresiones o de clicks utilizados',
  LIMITE smallint(4) NOT NULL DEFAULT '1' COMMENT 'limite de impresiones o clicks limitados',
  ESTATUS enum('A','I','R') NOT NULL DEFAULT 'A' COMMENT 'estatus del registro',
  FECHA datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT 'fecha en que se realizo el enlace'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='registros modulo enlaces patrocinados';

lp2008_excedidos;
CREATE TABLE lp2008_excedidos (
  USUARIO_ID mediumint(11) NOT NULL,
  FECHA datetime NOT NULL,
  CANTIDAD smallint(6) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

lp2008_expreso;
CREATE TABLE lp2008_expreso (
  ID int(11) NOT NULL,
  USUARIO_ID mediumint(11) NOT NULL,
  ARTICULO_ID mediumint(9) NOT NULL,
  UID mediumint(9) NOT NULL COMMENT 'UID DE LA PUBLCIACION',
  SMS enum('S','N') NOT NULL DEFAULT 'N' COMMENT 'SI FUE ENVIADO SMS',
  MONTORESALTADO decimal(8,0) NOT NULL DEFAULT '0' COMMENT 'MONTO RECIBIDO POR RESALTADO',
  FECHA date NOT NULL,
  COMENTARIO varchar(50) DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

lp2008_extensiones;
CREATE TABLE lp2008_extensiones (
  ID mediumint(9) NOT NULL,
  USUARIO_ID mediumint(9) NOT NULL,
  FECHA datetime NOT NULL,
  HASTA datetime DEFAULT NULL,
  PROCESADO datetime DEFAULT NULL,
  EXTENSION smallint(6) DEFAULT NULL,
  ESTATUS enum('P','A','C') NOT NULL DEFAULT 'P',
  COMENTARIO text
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='ASIGNA LIMITE PUBLICACION POR USUARIO ESPECIFICO';

CREATE TABLE lp2008_faq (
  ID smallint(6) NOT NULL,
  ORDEN tinyint(4) NOT NULL,
  CATEGORIA varchar(15) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  TOPICO varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  DESCRIPCION text COLLATE utf8_unicode_ci NOT NULL,
  ESTATUS enum('A','I') COLLATE utf8_unicode_ci NOT NULL DEFAULT 'A',
  VISITAS smallint(6) NOT NULL DEFAULT '0',
  VISITADO datetime NOT NULL DEFAULT '0000-00-00 00:00:00'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='CONTIENE LAS PREGUNTAS Y RESPUESTAS PARA LA AYUDA';

lp2008_favoritas;
CREATE TABLE lp2008_favoritas (
  ID mediumint(9) NOT NULL,
  ESTATUS enum('A','I') NOT NULL DEFAULT 'A',
  USUARIO_ID varchar(70) DEFAULT NULL,
  ARTICULO_ID mediumint(9) NOT NULL DEFAULT '0',
  FECHA timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='ARTICULOS SELECCIONADOS COMO FAVORITOS POR LOS USUARIOS';

lp2008_financieras;
CREATE TABLE lp2008_financieras (
  ID smallint(6) NOT NULL,
  FECHA datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT 'FECHA REGISTRADA',
  NOMBRE varchar(40) NOT NULL,
  EMAIL varchar(120) NOT NULL,
  TELEFONO1 varchar(14) NOT NULL,
  TELEFONO2 varchar(14) NOT NULL,
  CONTACTO varchar(40) NOT NULL,
  PROVINCIA smallint(6) NOT NULL,
  DIRECCION text NOT NULL,
  UBICACION text NOT NULL,
  MINIMO double(15,2) NOT NULL DEFAULT '0.00',
  TIPO varchar(20) NOT NULL DEFAULT 'VEH' COMMENT 'TIPO DE FINANCIERA',
  ESTATUS enum('A','I') NOT NULL DEFAULT 'A'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='CONTIENE LOS NOMBRES DE LAS ENTIDADES FINANCIERAS';

lp2008_finantipo;
CREATE TABLE lp2008_finantipo (
  FINANCIERA_ID mediumint(10) NOT NULL,
  TIPO enum('BR','VEH','PER','OTR','PYME') NOT NULL DEFAULT 'VEH',
  ANIO smallint(6) NOT NULL DEFAULT '1985'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='FINANCIERAS POR TIPOS';

lp2008_impresiones;
CREATE TABLE lp2008_impresiones (
  SECCION smallint(6) NOT NULL COMMENT 'SECCION DE LA IMPRESION',
  CATEGORIA_ID smallint(6) NOT NULL COMMENT 'CATEGORIA DE LA SECCION',
  FECHA date NOT NULL DEFAULT '0000-00-00',
  CANTIDAD mediumint(9) NOT NULL DEFAULT '1'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='ALMACENA LAS IMPRESIONES POR SECCION';

lp2008_ip2c;
CREATE TABLE lp2008_ip2c (
  id int(10) UNSIGNED NOT NULL,
  begin_ip varchar(20) DEFAULT NULL,
  end_ip varchar(20) DEFAULT NULL,
  begin_ip_num int(11) UNSIGNED DEFAULT NULL,
  end_ip_num int(11) UNSIGNED DEFAULT NULL,
  country_code varchar(3) DEFAULT NULL,
  country_name varchar(150) DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

lp2008_linkaplan;
CREATE TABLE lp2008_linkaplan (
  ID smallint(6) NOT NULL,
  ARTICULO_ID int(11) NOT NULL,
  TIPO enum('T','D','I') NOT NULL DEFAULT 'T' COMMENT 'TIPO DE PLAN DEL USUARIO',
  HASTA datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  CLICKS varchar(50) NOT NULL COMMENT 'CANTIDAD DE CLICKS RECIBIDOS ',
  ESTATUS enum('A','I') NOT NULL DEFAULT 'A'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='ARTICULOS QUE ENLAZAN A USUARIOS CON PLANES TI DE IN';

lp2008_listanegra;
CREATE TABLE lp2008_listanegra (
  ID smallint(6) NOT NULL,
  TIPO varchar(10) NOT NULL,
  VALOR varchar(35) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='ALMACENA LOS VALORES DE CAMPOS EN LISTA NEGRA';


CREATE TABLE lp2008_log_acciones (
  ID mediumint(9) NOT NULL,
  USUARIO_ID mediumint(9) NOT NULL DEFAULT '0',
  FECHA datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  ACCION varchar(20) NOT NULL DEFAULT '',
  DOCUMENTO varchar(20) NOT NULL DEFAULT ''
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='ALMACENA LAS ACCIONES HECHAS POR LOS OPERADORES';

lp2008_log_buscar;
CREATE TABLE lp2008_log_buscar (
  ID int(11) NOT NULL,
  FECHA datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  STR varchar(60) NOT NULL DEFAULT '',
  TIPOB enum('S','N') NOT NULL DEFAULT 'S',
  CANTIDAD mediumint(9) NOT NULL DEFAULT '0' COMMENT 'cantidad registros encontrados',
  BUSQUEDAS smallint(6) NOT NULL DEFAULT '1' COMMENT 'BUSQUEDAS REALIZADAS DE ESE TEXTO ',
  USUARIO varchar(70) NOT NULL DEFAULT '' COMMENT 'USUARIO QUE HACE BUSQUEDA',
  URL varchar(70) NOT NULL DEFAULT ''
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='ALMACENA STRING DE BUSQUEDA ';

lp2008_log_click;
CREATE TABLE lp2008_log_click (
  ID int(11) NOT NULL,
  FECHA datetime NOT NULL,
  USUARIO_ID int(11) NOT NULL,
  URLBASE varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  URL varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  TEXTO varchar(255) COLLATE utf8_unicode_ci NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='ALMACENA LOS LOGS DE CLICKS ';

lp2008_log_emailactual;
CREATE TABLE lp2008_log_emailactual (
  ID mediumint(9) NOT NULL,
  USUARIO_ID mediumint(9) NOT NULL,
  FECHA datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT 'FECHA HECHA EL LOG',
  TIPO enum('A','C') NOT NULL DEFAULT 'A' COMMENT 'A = ACTUAL, C= CAMBIADO'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='CONTIENE LOS USUARIOS QUE CONFIRMARON SU EMAIL';

lp2008_log_envmsg;
CREATE TABLE lp2008_log_envmsg (
  ID mediumint(9) NOT NULL,
  ARTICULO_ID mediumint(9) NOT NULL,
  USUARIO_ID mediumint(9) NOT NULL,
  FECHA date NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='ALMACENA LA CANTIDAD DE MENSAJES ENVIADOS POR DIA';

lp2008_log_logins;
CREATE TABLE lp2008_log_logins (
  ID bigint(20) NOT NULL,
  USUARIO_ID bigint(20) NOT NULL DEFAULT '0',
  FECHA timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  IP varchar(25) CHARACTER SET latin1 NOT NULL DEFAULT '',
  TIPO enum('E','EM','EF','EFM','S','SM','EP') CHARACTER SET latin1 NOT NULL DEFAULT 'E' COMMENT 'LOG LAS ENTRADAS DESDE PC FB Y FB MOVIL',
  HOST varchar(100) CHARACTER SET latin1 NOT NULL,
  DISPOSITIVO enum('M','P') NOT NULL DEFAULT 'P',
  USUARIO varchar(70) NOT NULL COMMENT 'ALMACENA EL COOKIE DE LA MAQUINA'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='REGISTRA LAS ENTRADAS Y LAS SALIDAS DE LOS USUARIOS AL SISTE';

lp2008_log_notifica;
CREATE TABLE lp2008_log_notifica (
  ID smallint(6) NOT NULL,
  USUARIO_ID mediumint(9) NOT NULL DEFAULT '0',
  TIPO varchar(20) CHARACTER SET latin1 NOT NULL DEFAULT 'EXC',
  DOCUMENTO varchar(20) DEFAULT NULL COMMENT 'ALMACENA UN POSIBLE ID DEPENDE TIPO',
  FECHA datetime NOT NULL DEFAULT '0000-00-00 00:00:00'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='NOTIFICA ALGO QUE SE ENVIO A LOS USUARIOS';

lp2008_log_palabras;
CREATE TABLE lp2008_log_palabras (
  ID int(11) NOT NULL,
  USUARIO_ID bigint(20) NOT NULL DEFAULT '0',
  PALABRA int(11) NOT NULL DEFAULT '0',
  FECHA timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='ALMACENA PALABRAS MALAS PARA VERIFICAR';

lp2008_log_pines;
CREATE TABLE lp2008_log_pines (
  ID int(10) UNSIGNED NOT NULL COMMENT 'id del registro',
  CANTIDAD mediumint(8) UNSIGNED NOT NULL COMMENT 'cantidad de pines utilizados',
  MONTO int(10) UNSIGNED NOT NULL COMMENT 'cantidad de lo ofrecido por los pines dependiendo del modulo',
  IDTIPO int(10) UNSIGNED NOT NULL COMMENT 'id de la referencia del tipo',
  TIPO tinyint(3) UNSIGNED NOT NULL COMMENT 'modulo que utilizo el pin',
  FECHA datetime NOT NULL COMMENT 'fecha de cuando se realizo',
  IPADDRESS varchar(15) NOT NULL COMMENT 'direccion ip de donde se realizo',
  USUARIO_ID mediumint(9) UNSIGNED NOT NULL COMMENT 'usuario id de quien lo realizo',
  AUTOR mediumint(9) NOT NULL COMMENT 'autor que realizo la operacion (mismo usuario o ooperador))'
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='TABLA PARA GUARDAR LAS TRANSACCIONES DE LOS USO DE LOS PINES';


CREATE TABLE lp2008_log_prestamos (
  PRESTAMO_ID mediumint(9) NOT NULL,
  FINANCIERA_ID mediumint(9) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='PRESTAMOS ENVIADOS A ENTIDADES';

lp2008_log_pubusu;
CREATE TABLE lp2008_log_pubusu (
  USUARIO_ID mediumint(9) NOT NULL,
  CUANTOS mediumint(9) NOT NULL,
  FECHA date NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='ALMACENA CUANTAS PUBLICACIONES POR USUARIO';

lp2008_lpbonos;
CREATE TABLE lp2008_lpbonos (
  ID mediumint(9) NOT NULL,
  NUMERO varchar(20) NOT NULL DEFAULT '' COMMENT 'NUMERO GENERADO PARA EL BONO',
  USUARIO_ID varchar(70) NOT NULL DEFAULT '',
  ARTICULO_ID mediumint(9) NOT NULL DEFAULT '0',
  PC_ID varchar(70) NOT NULL DEFAULT '',
  NOMBRE varchar(40) NOT NULL DEFAULT '',
  TELEFONO varchar(14) NOT NULL,
  CELULAR varchar(14) NOT NULL,
  FECHA datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  DOCUMENTO varchar(20) NOT NULL DEFAULT '' COMMENT 'NUMERO DE FACTURA',
  VALOR decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT 'VALOR FACTURA',
  SESSION varchar(40) NOT NULL DEFAULT '' COMMENT 'SESSION DEL USUARIO PARA RECUPERAR EL CUPON',
  ESTATUS enum('A','P') NOT NULL DEFAULT 'A',
  COMENTARIO text NOT NULL COMMENT 'COMENTARIO ADICIONAL DE LA COMPRA'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='CONTIENE LOS CUPONES EMITIDOS PARA USUARIOS';

lp2008_lppuntos;
CREATE TABLE lp2008_lppuntos (
  ID mediumint(9) NOT NULL,
  ARTICULO_ID mediumint(9) NOT NULL DEFAULT '0',
  VALIDO enum('S','N','A') NOT NULL DEFAULT 'S',
  VALOR smallint(3) NOT NULL DEFAULT '0',
  FECHA timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='PUNTOS ASIGNADOS A LOS USUARIOS POR PUBLICAR ARTICULOS';

lp2008_mapxusu;
CREATE TABLE lp2008_mapxusu (
  USUARIO_ID mediumint(9) NOT NULL,
  ARTICULO_ID mediumint(9) NOT NULL DEFAULT '0',
  FECHA datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT 'ULTIMA ACTUALIZACION'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='ALMACENA LA CANTIDAD DE MAPAS POR USUARIO';

CREATE TABLE lp2008_marcas (
  ID smallint(6) NOT NULL,
  ID_VIEJO smallint(6) NOT NULL COMMENT 'ID VIEJO TEMPORAL PARA REAJUSTE',
  MARCA varchar(30) NOT NULL,
  TIPO enum('CE','VE') NOT NULL DEFAULT 'VE',
  ESTATUS enum('A','I') NOT NULL DEFAULT 'A',
  PUBLICADOS smallint(6) NOT NULL DEFAULT '0'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='CONTIENE LAS MARCAS VARIAS DEL SISTEMA';

lp2008_mensajeria;
CREATE TABLE lp2008_mensajeria (
  ID mediumint(9) NOT NULL,
  DE mediumint(9) NOT NULL DEFAULT '0',
  PARA mediumint(9) NOT NULL DEFAULT '0',
  NOMBRE varchar(90) NOT NULL,
  EMAIL varchar(100) NOT NULL COMMENT 'EMAIL EN QUE ENVIA ',
  TELEFONO varchar(14) DEFAULT NULL,
  ARTICULO_ID mediumint(9) NOT NULL DEFAULT '0',
  ASUNTO varchar(70) NOT NULL DEFAULT '',
  ESTATUSDE enum('I','N','L') NOT NULL DEFAULT 'N',
  ESTATUSPARA enum('I','N','L') NOT NULL DEFAULT 'N',
  FECHA datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MENSAJES smallint(6) NOT NULL DEFAULT '0'
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='TABLA PARA ALMACENAR MENSAJES ENVIADOS A USUARIOS DE OTROS';

lp2008_mensajes;
CREATE TABLE lp2008_mensajes (
  ID smallint(6) NOT NULL,
  MENSAJERIA_ID mediumint(9) NOT NULL,
  FECHA datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  TIPO enum('S','E') COLLATE utf8_unicode_ci NOT NULL DEFAULT 'E' COMMENT 'E- MSG ENTRADA, S - MSG SALIDA',
  ESTATUS enum('A','I') COLLATE utf8_unicode_ci NOT NULL DEFAULT 'A',
  DISPOSITIVO enum('M','D') COLLATE utf8_unicode_ci NOT NULL,
  MENSAJE text COLLATE utf8_unicode_ci NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='GUARDA LOS MENSAJES ENVIADOS Y RECIBIDOS POR USUARIOS';


CREATE TABLE lp2008_modelos (
  ID smallint(6) NOT NULL,
  ID_VIEJO smallint(6) NOT NULL COMMENT 'ID VIEJO TEMPORAL PARA REAJUSTE',
  MARCA_ID smallint(6) NOT NULL COMMENT 'ID DE LA MARCA',
  MODELO varchar(50) NOT NULL,
  TIPO enum('CE','VE') NOT NULL DEFAULT 'VE',
  ESTATUS enum('A','I') NOT NULL DEFAULT 'A',
  PUBLICADOS smallint(6) NOT NULL DEFAULT '0'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='CONTIENE LOS MODELOS VARI0S DEL SISTEMA';

lp2008_msgarticulo;
CREATE TABLE lp2008_msgarticulo (
  ID int(11) NOT NULL,
  ARTICULO_ID int(11) NOT NULL,
  USUARIO_ID int(11) NOT NULL,
  IPADDRESS varchar(30) COLLATE utf8_unicode_ci NOT NULL,
  FECHA datetime NOT NULL,
  NOMBRE varchar(40) COLLATE utf8_unicode_ci NOT NULL,
  TELEFONO varchar(14) COLLATE utf8_unicode_ci NOT NULL,
  MENSAJE varchar(100) COLLATE utf8_unicode_ci NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='ALMACENA LOS MENSAJES ENVIADOS A WHATSAPP POR UN ARTICULO';

lp2008_msgcintillo;
CREATE TABLE lp2008_msgcintillo (
  ID smallint(6) NOT NULL,
  TITULO varchar(50) NOT NULL COMMENT 'TITULO MENSAJE',
  MENSAJE varchar(300) NOT NULL,
  FECHA datetime NOT NULL,
  HASTA tinyint(4) NOT NULL COMMENT 'CANTIDAD DE DIAS',
  URL varchar(100) NOT NULL,
  ENLACE varchar(50) NOT NULL,
  TIPO enum('E','W','I') NOT NULL DEFAULT 'I',
  ESTATUS enum('A','I','M') NOT NULL DEFAULT 'A'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='CONTIENE LOS MENSAJES A SER COLOCADOS EN CINTILLO';

lp2008_municipios;
CREATE TABLE lp2008_municipios (
  ID int(11) NOT NULL,
  PROVINCIA_ID int(11) NOT NULL,
  MUNICIPIO varchar(50) NOT NULL,
  PUBLICADOS int(11) NOT NULL DEFAULT '0'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='CONTIENE LOS MUNICIPIOS PARA REGISTROS DE USUARIOS Y OTROS';

lp2008_nologin;
CREATE TABLE lp2008_nologin (
  ID smallint(6) NOT NULL,
  USUARIO_ID int(11) NOT NULL,
  PENALIDAD enum('R','C','IP','LE','PP','FE') CHARACTER SET latin1 NOT NULL DEFAULT 'R' COMMENT 'R - REPETIDOS, C- CAT INCORRECTA, IP - INCUMPLIMIENTO PAGO, LE - LIMITE EXCEDIDO, PP - PENDIENTE PAGO PLAN, FE - FOTOS ETIQUETAS',
  HASTA datetime NOT NULL,
  ESTATUS enum('A','I') NOT NULL DEFAULT 'A'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='CONTROLA SI EL USUARIO PUEDE HACER LOGIN O NO';

lp2008_notelefono;
CREATE TABLE lp2008_notelefono (
  ID int(11) NOT NULL,
  TELEFONO varchar(14) COLLATE utf8_unicode_ci NOT NULL,
  HASTA datetime NOT NULL,
  CANTIDAD smallint(6) NOT NULL DEFAULT '1',
  ESTATUS enum('A','I') COLLATE utf8_unicode_ci NOT NULL DEFAULT 'A'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='BLOQUEA NUMEROS DE TELEFONO REGISTRO';

lp2008_opcionales;
CREATE TABLE lp2008_opcionales (
  ID mediumint(9) NOT NULL,
  ARTICULO_ID mediumint(9) NOT NULL DEFAULT '1',
  HASTA datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  TIPO enum('V','VC','VM','VMC','PLP','PLC') NOT NULL DEFAULT 'V',
  ESTATUS enum('A','I','E') NOT NULL DEFAULT 'A',
  DIAS smallint(9) NOT NULL DEFAULT '1'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='ARTIICULOS QUE PAGAN PARA ESTAR VIP PRINCIPA Y CATEGORIA';

lp2008_palabras;
CREATE TABLE lp2008_palabras (
  PALABRA varchar(100) DEFAULT NULL,
  NIVEL enum('A','M','B') NOT NULL DEFAULT 'B',
  ESTATUS enum('A','I') NOT NULL DEFAULT 'A',
  FECHA datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CUANTOS smallint(6) NOT NULL DEFAULT '0'
) ENGINE=MyISAM DEFAULT CHARSET=utf8;


CREATE TABLE lp2008_parametros (
  PARAMETRO varchar(16) NOT NULL,
  VALOR varchar(300) DEFAULT NULL,
  DESCRIPCION varchar(40) NOT NULL COMMENT 'DESCRIPCION DEL PARAMETRO'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='CONTIENE LOS PARAMETROS DEL SISTEMA';

lp2008_paramsmvc;
CREATE TABLE lp2008_paramsmvc (
  PARAMETRO varchar(16) NOT NULL,
  VALOR varchar(80) NOT NULL,
  DESCRIPCION varchar(40) NOT NULL COMMENT 'DESCRIPCION DEL PARAMETRO'
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='CONTIENE LOS PARAMETROS DEL SISTEMA';

CREATE TABLE lp2008_pclaves (
  CATEGORIA_ID tinyint(4) NOT NULL DEFAULT '0',
  PCLAVES text NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='ALMACENA TODAS LAS PALABRAS CLAVES POR CATEGORIA';


CREATE TABLE lp2008_penalidades (
  ID smallint(6) NOT NULL,
  USUARIO_ID int(11) NOT NULL,
  OPERADOR_ID mediumint(9) NOT NULL DEFAULT '1' COMMENT 'OPERADOR QUE PENALIZA',
  PENALIDAD enum('R','C','IP','LE','PP','FE','PAR','PAC','PAIP','PALE','PAPP','PAFE','PAPV','PAVP') NOT NULL DEFAULT 'R' COMMENT 'R - REPETIDOS, C- CAT INCORRECTA, IP - INCUMPLIMIENTO PAGO, LE - LIMITE EXCEDIDO, PP - PENDIENTE PAGO PLAN, PA - PREAVISO\r\nPAPV - PRODUCTO VENCIDO\r\nPAVP - PRODUCTO A VENCER',
  DIAS smallint(6) NOT NULL DEFAULT '2',
  FECHA datetime NOT NULL,
  HASTA datetime NOT NULL,
  INTENTOS smallint(6) NOT NULL DEFAULT '0',
  ULTIMO datetime DEFAULT NULL,
  ESTATUS enum('A','I') NOT NULL DEFAULT 'A',
  COMENTARIO varchar(150) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='CONTROLA SI EL USUARIO PUEDE HACER LOGIN O NO';

lp2008_planenlista;
CREATE TABLE lp2008_planenlista (
  ID int(11) NOT NULL,
  USUARIO_ID mediumint(9) NOT NULL COMMENT 'id del usuario',
  CATEGORIA_ID smallint(6) NOT NULL,
  CPMACTUAL int(11) NOT NULL DEFAULT '0' COMMENT 'cantidad de impresiones actual',
  CPMHASTA int(11) DEFAULT NULL COMMENT 'limite de cantidad de impresiones',
  ESTATUS enum('A','I','R') DEFAULT 'A',
  FECHA_INICIO datetime NOT NULL COMMENT 'inicio de la campana',
  FECHA_FINAL datetime DEFAULT NULL COMMENT 'termino de la campana'
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='TABLA QUE GUARDARA LOS REGISTRO DE LAS PLANES EN LISTA';

lp2008_planes;
CREATE TABLE lp2008_planes (
  USUARIO_ID mediumint(9) NOT NULL DEFAULT '0',
  PLAN enum('OP1','OP2','LPE','LP','LP+','T1','T2','T3','TA','DV1','DV2','DV3','DV4','IN1','IN2','IN3','IN4') NOT NULL DEFAULT 'LP',
  INICIO datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT 'INICIO DEL PLAN ACTIVO',
  HASTA datetime DEFAULT '0000-00-00 00:00:00',
  ESTATUS enum('A','P','C','V') NOT NULL DEFAULT 'P'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='INFORMACION SOBRE LOS PLANES ADQUIRIDOS, LP, UV, ETC';


CREATE TABLE lp2008_planesinfo (
  USUARIO_ID mediumint(9) NOT NULL DEFAULT '0',
  LAT varchar(25) DEFAULT NULL COMMENT 'LATITUD COORD',
  LNG varchar(25) DEFAULT NULL COMMENT 'LONGITUD COORD',
  TIPO tinyint(2) NOT NULL,
  NOMBRE varchar(40) NOT NULL DEFAULT '' COMMENT 'NOMBRE DE LA TIENDA',
  RNC varchar(14) DEFAULT NULL COMMENT 'RNC DEL USUARIO O CLIENTE',
  LOGO varchar(1) NOT NULL DEFAULT 'N',
  HORARIO smallint(6) DEFAULT '0',
  FACILIDADES varchar(15) DEFAULT NULL COMMENT 'FACILIDADES DE LA TIENDA AL CLIENTE',
  URLVIDEO varchar(120) DEFAULT NULL,
  URLPAGINA varchar(100) DEFAULT NULL,
  URLFB varchar(100) DEFAULT NULL,
  URLIG varchar(100) DEFAULT NULL,
  PAYPAL varchar(100) DEFAULT NULL,
  PAYPAL_ACEPTA enum('S','N') NOT NULL DEFAULT 'N',
  PAYPAL_API_USERNAME varchar(100) DEFAULT NULL,
  PAYPAL_API_PASSWORD varchar(100) DEFAULT NULL,
  PAYPAL_API_SIGNATURE varchar(100) DEFAULT NULL,
  VISITAS bigint(6) NOT NULL DEFAULT '0',
  VISITADA datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  MAPA varchar(250) DEFAULT NULL,
  DESCRIPCION varchar(254) DEFAULT NULL COMMENT 'DESCRIPCION DE LAS TIENDAS'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='INF. SOBRE LAS TIENDAS, DEALERS';

lp2008_porprv;
CREATE TABLE lp2008_porprv (
  PROVINCIA_ID smallint(6) NOT NULL,
  PUBLICACIONES smallint(6) NOT NULL DEFAULT '0',
  TIENDAS smallint(6) NOT NULL DEFAULT '0',
  DEALERS smallint(6) NOT NULL DEFAULT '0',
  INMOBILIARIAS smallint(6) NOT NULL DEFAULT '0',
  USUARIOS smallint(6) NOT NULL DEFAULT '0'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='CONTIENE LAS CANTIDADES POR PROVINCIAS';

lp2008_prestamos;
CREATE TABLE lp2008_prestamos (
  ID mediumint(10) NOT NULL,
  NOMBRE varchar(40) NOT NULL,
  CEDULA varchar(15) NOT NULL,
  TELEFONO1 varchar(25) NOT NULL,
  TELEFONO2 varchar(15) NOT NULL,
  EMAIL varchar(60) NOT NULL,
  TIPO enum('BR','VEH','PER','OTR','PYME') NOT NULL DEFAULT 'VEH',
  TIPOINFO varchar(100) NOT NULL,
  MARCA varchar(20) NOT NULL,
  MODELO varchar(20) NOT NULL,
  ANIO varchar(4) NOT NULL,
  FECHA datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  CREDITO enum('Si','No','0') NOT NULL DEFAULT '0',
  INGRESOS double(15,2) NOT NULL,
  VALOR decimal(15,2) NOT NULL,
  MONTO decimal(15,2) NOT NULL,
  OTORGADO decimal(15,2) NOT NULL DEFAULT '0.00',
  FECHAOTOR date NOT NULL DEFAULT '0000-00-00',
  ENTIDADOTOR tinyint(4) NOT NULL DEFAULT '0',
  ESTATUS enum('S','R','C','P','I','D') NOT NULL DEFAULT 'I' COMMENT 'I - incompletos S - solicitud completar C - SOLICITUD CANCELADA P - SOLICITUD APROBADA POR FINANCIERA D - SOLICITUD DESEMBOLSADA',
  FASE tinyint(4) NOT NULL COMMENT 'FASE EN LA QUE VA EL EXPEDIENTE',
  COMENTARIO text NOT NULL,
  EVALUACION text CHARACTER SET latin1
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

lp2008_provincias;
CREATE TABLE lp2008_provincias (
  ID int(11) NOT NULL,
  ID_VIEJO int(11) NOT NULL,
  PROVINCIA varchar(30) NOT NULL,
  PUBLICADOS int(11) NOT NULL DEFAULT '0'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='CONTIENE LISTADO DE PROVINCIAS';

lp2008_publicados;
CREATE TABLE lp2008_publicados (
  FECHA date NOT NULL DEFAULT '0000-00-00',
  CUANTOS smallint(6) NOT NULL DEFAULT '0'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='ALMACENA TOTAL PUBLICADOS POR DIA';

lp2008_publimite;
CREATE TABLE lp2008_publimite (
  ID mediumint(9) NOT NULL,
  USUARIO_ID mediumint(9) NOT NULL,
  FECHA datetime NOT NULL,
  HASTA datetime NOT NULL,
  EXTENSION tinyint(4) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='ASIGNA LIMITE PUBLICACION POR USUARIO ESPECIFICO';

lp2008_recientes;
CREATE TABLE lp2008_recientes (
  ARTICULO_ID mediumint(9) NOT NULL,
  USUARIO varchar(70) NOT NULL,
  FECHA datetime NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='ARTICULOS VISITADOS RECIENTEMENTE';

lp2008_recurrentes;
CREATE TABLE lp2008_recurrentes (
  USUARIO_ID mediumint(9) NOT NULL,
  INICIO date NOT NULL DEFAULT '0000-00-00' COMMENT 'INICIO DE LA MODALIDAD',
  MODIFICA datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT 'SE REALIZA MODIFICACION DEL REGISTRO, ESTATUS, FORMA DE PAGO',
  FORMAPAGO enum('TP','TR','MM','LPP','TU','UR','PP','PU','CK','EF','RE') NOT NULL COMMENT 'FORMA DE PAGO A UTILIZAR DE FORMA MENSUAL',
  DURACION smallint(6) NOT NULL DEFAULT '12',
  ESTATUS enum('A','I','C') NOT NULL DEFAULT 'I',
  DIA smallint(6) NOT NULL DEFAULT '1',
  NCF enum('S','N') NOT NULL DEFAULT 'N',
  COMENTARIO text NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='ALMACENA USUARIOS MODALIDAD PAGOS MENSUALES';

lp2008_referidos;
CREATE TABLE lp2008_referidos (
  ID int(6) NOT NULL,
  REFERIDO mediumint(9) NOT NULL,
  REFERIDOR mediumint(9) NOT NULL,
  FECHA datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  REGISTRO enum('S','N') DEFAULT 'N',
  PUBLICA enum('S','N') NOT NULL DEFAULT 'N',
  ESTATUS enum('A','I') NOT NULL DEFAULT 'A',
  CANAL enum('WS','EM','OT') NOT NULL DEFAULT 'OT' COMMENT 'POR QUE VIA FUE REFERIDO'
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='USUARIOS REFERIDOS POR OTROS';

lp2008_referidosold;
CREATE TABLE lp2008_referidosold (
  ID smallint(6) NOT NULL,
  TIPO enum('I','X') NOT NULL DEFAULT 'I',
  NOMBRE varchar(60) NOT NULL DEFAULT '',
  EMAIL varchar(60) NOT NULL DEFAULT '',
  FECHA datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  REFERIDO varchar(60) NOT NULL DEFAULT '',
  PROCESADO enum('N','S') NOT NULL DEFAULT 'N'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='USUARIOS REFERIDOS POR OTROS';

lp2008_renomultiples;
CREATE TABLE lp2008_renomultiples (
  USUARIO_ID mediumint(9) NOT NULL,
  HASTA datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT 'HASTA VALIDEZ',
  ESTATUS enum('A','I') NOT NULL DEFAULT 'A'
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='CONTIENE LAS HORAS DE LAS RENOVACIONES AUTOMATICAS MULTIPLES DIARIAS';

lp2008_renovaarticulo;
CREATE TABLE lp2008_renovaarticulo (
  ID bigint(9) NOT NULL,
  ARTICULO_ID mediumint(9) NOT NULL DEFAULT '0',
  ANTERIOR datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  ACTUAL datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  VISITAS smallint(6) NOT NULL DEFAULT '1'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='CONTROL DE ARTICULOS RENOVADOS';


CREATE TABLE lp2008_renovaciones (
  USUARIO_ID mediumint(9) NOT NULL,
  PLAN enum('PB','LP','LP+','T1','T2','T3','TA','DV1','DV2','DV3','DV4','IN1','IN2','IN3','IN4') NOT NULL DEFAULT 'PB' COMMENT 'PLAN DE USUARIO',
  TIPO enum('SR','RAM') NOT NULL DEFAULT 'SR' COMMENT 'SIMPLES Y MULTIPLES',
  HASTA datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT 'HASTA VALIDEZ',
  ESTATUS enum('A','I') NOT NULL DEFAULT 'A',
  LUNES tinyint(4) NOT NULL,
  MARTES tinyint(4) NOT NULL,
  MIERCOLES tinyint(4) NOT NULL,
  JUEVES tinyint(4) NOT NULL,
  VIERNES tinyint(4) NOT NULL,
  SABADO tinyint(4) NOT NULL,
  DOMINGO tinyint(4) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='CONTIENE LAS HORAS DE LAS RENOVACIONES AUTOMATICAS DIARIAS';

lp2008_repuemarca;
CREATE TABLE lp2008_repuemarca (
  REPUESTO_ID mediumint(10) NOT NULL,
  MARCA varchar(30) NOT NULL COMMENT 'MARCA DE VEHICULOS QUE TRABAJA EL REPUESTO'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='REPUESTOS POR MARCAS';

lp2008_repuestos;
CREATE TABLE lp2008_repuestos (
  ID smallint(6) NOT NULL,
  NOMBRE varchar(40) NOT NULL,
  EMAIL varchar(120) NOT NULL,
  TELEFONO1 varchar(14) DEFAULT NULL,
  TELEFONO2 varchar(14) CHARACTER SET latin1 DEFAULT NULL COMMENT 'TELEFONO MOVIL',
  CONTACTO varchar(40) NOT NULL,
  PROVINCIA smallint(6) NOT NULL,
  DIRECCION varchar(200) NOT NULL,
  FECHA datetime NOT NULL COMMENT 'FECHA DEL REGISTRO',
  ESTATUS enum('A','I') NOT NULL DEFAULT 'A'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='CONTIENE LOS NOMBRES DE LOS REPUESTOS ';

lp2008_sectores;
CREATE TABLE lp2008_sectores (
  ID smallint(6) NOT NULL,
  PROVINCIA_ID smallint(6) NOT NULL DEFAULT '0',
  PROVINCIA_IDN int(11) NOT NULL COMMENT 'ID NUEVO DE PROVINCIA',
  MUNICIPIO_ID int(11) NOT NULL,
  SECTOR varchar(90) NOT NULL DEFAULT '',
  PUBLICADOS_BR smallint(6) NOT NULL DEFAULT '0'
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

lp2008_sectoresn;
CREATE TABLE lp2008_sectoresn (
  ID smallint(6) NOT NULL,
  PROVINCIA_ID smallint(6) NOT NULL DEFAULT '0',
  PROVINCIA_IDN int(11) NOT NULL COMMENT 'ID NUEVO DE PROVINCIA',
  MUNICIPIO_ID int(11) NOT NULL,
  SECTOR varchar(90) NOT NULL DEFAULT '',
  PUBLICADOS_BR smallint(6) NOT NULL DEFAULT '0'
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

lp2008_servicios;
CREATE TABLE lp2008_servicios (
  ID mediumint(9) NOT NULL,
  ESTATUS enum('A','I') NOT NULL DEFAULT 'A',
  USUARIO_ID mediumint(9) NOT NULL,
  TIPO enum('E','P') NOT NULL DEFAULT 'E' COMMENT 'E - EMPRESA, P - PERSONA',
  CREADA datetime NOT NULL,
  VISITADO datetime DEFAULT NULL,
  VISITAS smallint(6) DEFAULT NULL,
  OPCIONAL enum('R','N') NOT NULL DEFAULT 'N' COMMENT 'INDICA SI RESALTA O NO EL SERVICIO',
  OPCHASTA datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT 'HASTA CUANDO ESTARA RESALTADO',
  NOMBRE varchar(60) NOT NULL,
  LOGO enum('S','N') NOT NULL DEFAULT 'N' COMMENT 'CONTIENE LOGO O NO',
  TELEFONO1 varchar(22) NOT NULL,
  TELEFONO2 varchar(22) NOT NULL,
  TELEFONO3 varchar(22) NOT NULL,
  BBPIN varchar(8) DEFAULT NULL,
  EMAIL varchar(100) NOT NULL,
  URL varchar(100) NOT NULL,
  URLVIDEO varchar(120) NOT NULL COMMENT 'VIDEO DEL SERVICIO',
  DIRECCION varchar(100) NOT NULL,
  SECTOR varchar(60) NOT NULL,
  PROVINCIA varchar(40) NOT NULL,
  MUNICIPIO smallint(6) NOT NULL,
  DESCRIPCION varchar(150) NOT NULL,
  CATEGORIA_ID mediumint(9) NOT NULL,
  SERVICIO varchar(50) NOT NULL,
  SERVICIO_ID smallint(6) NOT NULL,
  RATING tinyint(4) NOT NULL DEFAULT '0' COMMENT 'RATING DEL SERVICIO',
  LAT varchar(25) DEFAULT NULL COMMENT 'LATITUD COORD',
  LNG varchar(25) DEFAULT NULL COMMENT 'LONGITUD COORD',
  MAPA enum('S','N') NOT NULL DEFAULT 'S' COMMENT 'PERMITE MOSTRAR MAPA O NO',
  IPADDRESS varchar(14) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='ALMACENA NEGOCIOS O EMPRESAS QUE BRINDAS SERVICIOS';

lp2008_servicioscat;
CREATE TABLE lp2008_servicioscat (
  ID smallint(6) NOT NULL,
  CATEGORIA_ID smallint(6) NOT NULL,
  SERVICIO varchar(50) NOT NULL,
  PUBLICADOS smallint(6) NOT NULL DEFAULT '0'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='ALMACENA LAS CATEGORIAS POR SERVICIOS';

lp2008_sitemap;
CREATE TABLE lp2008_sitemap (
  ULTIMO int(11) NOT NULL DEFAULT '0',
  ORDEN smallint(6) NOT NULL DEFAULT '0'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='ALMACENA DATOS DE LA CREACION SITEMAP';

lp2008_sitemapindex;
CREATE TABLE lp2008_sitemapindex (
  ID smallint(6) NOT NULL,
  INICIO mediumint(9) NOT NULL,
  FINAL mediumint(9) NOT NULL,
  MODIFICADO date NOT NULL,
  CUANTOS mediumint(9) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='ALMACENA LOS SITEMAPS GENERADOS POR EL CRON';

lp2008_solpiezas;
CREATE TABLE lp2008_solpiezas (
  ID mediumint(10) NOT NULL,
  NOMBRE varchar(40) NOT NULL,
  TELEFONO1 varchar(15) NOT NULL,
  TELEFONO2 varchar(15) NOT NULL,
  EMAIL varchar(60) NOT NULL,
  PROVINCIA tinyint(4) NOT NULL COMMENT 'PROVINCIA DE LA SOLICITUD DE PIEZAS',
  MARCA varchar(20) NOT NULL,
  MODELO varchar(20) NOT NULL,
  ANIO varchar(4) NOT NULL,
  PIEZA text NOT NULL COMMENT 'DESCRIPCION DE LA PIEZA DE VEHICULO',
  SEGUIMIENTO text,
  FECHA datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  ESTATUS enum('S','R','C','P') NOT NULL DEFAULT 'S'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='SOLICITUDES DE PIEZAS PARA LOS VEHICULOS EN REPUESTOS';

lp2008_subcategorias;
CREATE TABLE lp2008_subcategorias (
  ID smallint(6) NOT NULL,
  CATEGORIA_ID smallint(6) NOT NULL DEFAULT '0',
  SUBCATEGORIA varchar(80) NOT NULL,
  PUBLICADOS smallint(6) NOT NULL DEFAULT '0'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='SUBCATEGORIAS DE LOS ARTICULOS';

lp2008_subplan;
CREATE TABLE lp2008_subplan (
  USUARIO_ID mediumint(9) NOT NULL DEFAULT '0',
  SUBCATEGORIA_ID mediumint(9) NOT NULL DEFAULT '0',
  PUBLICADOS smallint(6) NOT NULL DEFAULT '0'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='SUBCATEGORIAS POR TIENDAS';

lp2008_subtienda;
CREATE TABLE lp2008_subtienda (
  USUARIO_ID mediumint(9) NOT NULL DEFAULT '0',
  SUBCATEGORIA_ID mediumint(9) NOT NULL DEFAULT '0',
  PUBLICADOS smallint(6) NOT NULL DEFAULT '0'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='SUBCATEGORIAS POR TIENDAS';

lp2008_sugiere;
CREATE TABLE lp2008_sugiere (
  ARTICULO varchar(70) NOT NULL DEFAULT ''
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='ALMACENA SUGERENCIAS DE BUSQUEDAS BASADAS EN TITULOS';

lp2008_tempcuentas;
CREATE TABLE lp2008_tempcuentas (
  TELEFONO varchar(14) CHARACTER SET utf8 NOT NULL,
  CUENTAS int(11) NOT NULL DEFAULT '1'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='TEMPORAL PARA CONTABILIZAR CUENTAS';

lp2008_tiendas;
CREATE TABLE lp2008_tiendas (
  USUARIO_ID mediumint(9) NOT NULL DEFAULT '0',
  PROVINCIA smallint(6) NOT NULL,
  TIPO tinyint(2) NOT NULL,
  NOMBRE varchar(40) NOT NULL DEFAULT '' COMMENT 'NOMBRE DE LA TIENDA',
  PALABRAS varchar(120) NOT NULL DEFAULT '' COMMENT 'PALABRAS CLAVES A UTILIZAR',
  DESCRIPCION varchar(254) NOT NULL DEFAULT '' COMMENT 'DESCRIPCION DE LAS TIENDAS',
  PUBLICADOS smallint(6) NOT NULL DEFAULT '0' COMMENT 'CANTIDAD ARTICULOS PUBLICADOS',
  VISITAS smallint(6) NOT NULL DEFAULT '0',
  VISITADA datetime NOT NULL DEFAULT '0000-00-00 00:00:00'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='INF. SOBRE LAS TIENDAS';


CREATE TABLE lp2008_transacciones (
  ID smallint(6) NOT NULL,
  RENOVACIONES enum('S','N') NOT NULL DEFAULT 'N',
  USUARIO_ID mediumint(9) NOT NULL DEFAULT '0',
  OPERADOR_ID mediumint(9) DEFAULT NULL COMMENT 'OPERADOR QUE APROBO PRODUCTO',
  TIPO enum('CP','SR','RAM','OP1','OP2','LP','LP+','T1','T2','T3','TA','DV1','DV2','DV3','DV4','IN1','IN2','IN3','IN4','AO') CHARACTER SET latin1 DEFAULT 'CP' COMMENT 'TIPO DE POSIBLES TRASACCIONES',
  PRODUCTO enum('LP+','DEA','TIE','INM','RA','RAM','AO','CP') NOT NULL DEFAULT 'CP',
  VALOR decimal(12,2) NOT NULL DEFAULT '0.00',
  DESCUENTO float(5,2) NOT NULL DEFAULT '0.00',
  ITBIS float(7,2) NOT NULL DEFAULT '0.00' COMMENT 'ALMACENA ITBIS COBRADO',
  TASA float(4,2) NOT NULL DEFAULT '0.00',
  CANTIDAD smallint(6) DEFAULT NULL,
  BALANCE tinyint(4) NOT NULL DEFAULT '0',
  FORMAPAGO enum('TB','TP','TR','MM','LPP','TU','UR','PP','PU','CK','EF','RE','PIN','IC','PC') CHARACTER SET latin1 NOT NULL DEFAULT 'EF' COMMENT 'PC = Pines cortesia',
  NCF varchar(25) NOT NULL COMMENT 'NCF TRANSACCION',
  TRANSACCION text NOT NULL,
  ESTATUS enum('A','P','C') NOT NULL DEFAULT 'P',
  FECHA datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  PROCESADO datetime NOT NULL DEFAULT '0000-00-00 00:00:00'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='ALMACENA LAS TRANSACCIONES TANTO PARA COMPRA DE PINES COMO P';


CREATE TABLE lp2008_usuarios (
  ID mediumint(9) NOT NULL,
  EMAIL varchar(100) NOT NULL DEFAULT '',
  EMAILVALIDO enum('S','N') NOT NULL DEFAULT 'S' COMMENT 'DETERMINA SI EL EMAIL ES VALIDO PARA ENVIO CORREO',
  ESTATUS enum('A','I','R') NOT NULL DEFAULT 'I',
  NUEVOPASS enum('S','N') NOT NULL DEFAULT 'S',
  PASSWORD varchar(55) NOT NULL DEFAULT '',
  USUARIO varchar(35) NOT NULL DEFAULT '',
  USUPLAN enum('PB','OP1','OP2','LPE','LP','LP+','T1','T2','T3','TA','DV1','DV2','DV3','DV4','IN1','IN2','IN3','IN4') NOT NULL DEFAULT 'PB' COMMENT 'CONTIENE EL PLAN ACTUAL CONTROL LISTADOS',
  USUPLANN enum('PB','OP1','OP2','LPE','LP','LP+','TIE','DEA','INM') NOT NULL DEFAULT 'PB',
  USUHASTA datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT 'HASTA VIGENCIA PLAN',
  PAGA enum('S','N') NOT NULL DEFAULT 'N' COMMENT 'USUARIO QUE PAGA PLAN O PINES',
  FBUSUARIO varchar(50) NOT NULL COMMENT 'USUARIO DE FACEBOOK',
  FBUID bigint(20) NOT NULL COMMENT 'ID DE USUARIO EN FACEBOOK',
  FBAUTHFP enum('S','N') NOT NULL DEFAULT 'S' COMMENT 'AUTORIZA SI MOSTRAR FOTO O NO DE PERFIL',
  TWUSUARIO varchar(25) DEFAULT NULL COMMENT 'USUARIO DE TWITTER PARA SEGUIR',
  NOMBRE varchar(45) NOT NULL DEFAULT '',
  TELEFONO1 varchar(14) DEFAULT NULL,
  DIRECCION varchar(150) NOT NULL DEFAULT '',
  TELEFONO2 varchar(14) DEFAULT NULL,
  WHATSAPP enum('S','N') NOT NULL DEFAULT 'S',
  PROVINCIA smallint(6) NOT NULL DEFAULT '0',
  MUNICIPIO smallint(6) NOT NULL,
  PAIS varchar(2) NOT NULL DEFAULT 'DO',
  SECTOR smallint(6) NOT NULL DEFAULT '1',
  NACIMIENTO date NOT NULL DEFAULT '0000-00-00',
  SEXO enum('F','M') NOT NULL DEFAULT 'M',
  TELEFONO3 varchar(25) DEFAULT NULL,
  SESSION varchar(40) NOT NULL DEFAULT '',
  CREADA datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  ACTIVADA datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  FECHALOGIN datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  IPADDRESS varchar(40) NOT NULL,
  BALANCE smallint(12) NOT NULL DEFAULT '0',
  FECHABALANCE datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  REGISTRADO enum('M','P','MLPE','MNR','PNR','FP','FM','OP','KLK') NOT NULL DEFAULT 'P' COMMENT 'DETERMINA DESDE DONDE FUE EL REGISTRO, MOVIL O PC, FACEBOOK',
  PUBLICACIONES smallint(6) NOT NULL DEFAULT '0' COMMENT 'ARTICULOS PUBLICADOS',
  PUBLICACIONESRU int(11) NOT NULL DEFAULT '0' COMMENT 'RETIRADAS POR USUARIO',
  PUBLICACIONESRO int(11) NOT NULL DEFAULT '0' COMMENT 'RETIRADAS OPERADOR',
  CUENTAS mediumint(9) NOT NULL DEFAULT '1' COMMENT 'CANTIDAD DE CUENTAS CON EL MISMO NUMERO',
  RENOVOTODO datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  MENSAJES smallint(6) NOT NULL DEFAULT '0' COMMENT 'MENSAJES NUEVOS EN EL BUZON',
  FAVORITOS smallint(6) NOT NULL DEFAULT '0' COMMENT 'CANTDAD FAVORITOS',
  RECIBIR enum('S','N') NOT NULL DEFAULT 'S' COMMENT 'FLAG PARA RECIBIR EMAIL DE OTROS USUARIOS',
  PLANTILLA enum('S','N') NOT NULL DEFAULT 'N'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='TABLA QUE CONTIENE DATOS DE USUARIOS TANTO TIENDAS COMO OTRO';

lp2008_usubusca;
CREATE TABLE lp2008_usubusca (
  ID smallint(6) NOT NULL,
  USUARIO varchar(70) NOT NULL DEFAULT '',
  NOMBRE varchar(40) NOT NULL DEFAULT '',
  TELEFONO varchar(30) NOT NULL DEFAULT '',
  CELULAR varchar(15) CHARACTER SET latin1 DEFAULT NULL,
  EMAIL varchar(60) NOT NULL DEFAULT '',
  CATEGORIA smallint(6) NOT NULL DEFAULT '0',
  FECHA datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  COMENTARIO text NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='ALMACENA BUSQUEDAS DE USUARIOS PARA CONSEGUIR';

lp2008_usuproc;
CREATE TABLE lp2008_usuproc (
  ID tinyint(4) NOT NULL,
  USUARIO_ID smallint(6) NOT NULL DEFAULT '0',
  TIPO enum('P','M') NOT NULL DEFAULT 'M',
  FECHA datetime NOT NULL DEFAULT '0000-00-00 00:00:00'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='CONTIENE LOS USUARIOS PROCESADOS';

lp2008_usupromo;
CREATE TABLE lp2008_usupromo (
  USUARIO_ID mediumint(9) NOT NULL,
  PROMO varchar(20) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='ALMACENA LOS USUARIOS QUE REGISTRAN POR PROMO ENLACE';

lp2008_usutemp;
CREATE TABLE lp2008_usutemp (
  ID smallint(6) NOT NULL,
  EMAIL varchar(60) NOT NULL DEFAULT '',
  USUARIO varchar(25) NOT NULL DEFAULT '',
  NOMBRE varchar(45) NOT NULL DEFAULT '',
  PASSWORD varchar(55) NOT NULL DEFAULT '',
  ESTATUS enum('T','A') NOT NULL DEFAULT 'T',
  FECHA datetime NOT NULL DEFAULT '0000-00-00 00:00:00'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='TABLA TEMPORAL PARA REGISTRO DE USUARIOS';

lp2008_usuvisto;
CREATE TABLE lp2008_usuvisto (
  USUARIO_ID mediumint(9) NOT NULL,
  VISTO datetime NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='ALMACENA ULTIMO VISTO';

lp2008_vehiculos;
CREATE TABLE lp2008_vehiculos (
  ARTICULO_ID mediumint(9) NOT NULL DEFAULT '0',
  MARCAVE varchar(5) NOT NULL DEFAULT '',
  MODELO varchar(5) NOT NULL DEFAULT '',
  ANIO varchar(4) NOT NULL DEFAULT '',
  COLOREXT varchar(5) NOT NULL DEFAULT '0',
  COLORINT varchar(5) NOT NULL DEFAULT '0',
  PUERTAS enum('2','3','4','5') NOT NULL DEFAULT '4',
  PASAJEROS varchar(4) NOT NULL DEFAULT '0',
  COMBUSTIBLE varchar(5) NOT NULL DEFAULT '0',
  USO varchar(10) NOT NULL DEFAULT '0',
  TIPOUSO enum('K','M') NOT NULL DEFAULT 'K',
  TRACCION varchar(5) NOT NULL DEFAULT '',
  TRANSMISION varchar(5) NOT NULL DEFAULT '',
  ACCESORIOS varchar(60) NOT NULL COMMENT 'ACCESORIOS PARA LOS VEHICULOS, 1,2,3, ETC',
  ESTATUS enum('A','I') NOT NULL DEFAULT 'A'
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

lp2008_vehmarca;
CREATE TABLE lp2008_vehmarca (
  ID smallint(7) NOT NULL,
  MARCA varchar(30) NOT NULL DEFAULT '',
  PUBLICADOS smallint(6) NOT NULL DEFAULT '0'
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

lp2008_vehmodelo;
CREATE TABLE lp2008_vehmodelo (
  ID smallint(7) NOT NULL,
  MARCA_ID smallint(7) NOT NULL DEFAULT '0',
  MODELO varchar(30) NOT NULL DEFAULT '',
  PUBLICADOS smallint(6) NOT NULL DEFAULT '0'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='MODELOS DE VEHICULOS';

lp2008_vipmultiple;
CREATE TABLE lp2008_vipmultiple (
  ID mediumint(9) NOT NULL,
  ORDEN tinyint(4) NOT NULL COMMENT 'ORDEN DE LAS PUBLICACIONES ',
  SIGUIENTE smallint(6) NOT NULL COMMENT 'ID SIGUIENTE A SER COLOCADO',
  OPCIONAL_ID mediumint(9) NOT NULL COMMENT 'ID DEL OPCIONAL',
  USUARIO_ID int(11) NOT NULL,
  ARTICULO_ID mediumint(9) NOT NULL DEFAULT '1',
  DURACION smallint(6) NOT NULL DEFAULT '30' COMMENT 'DURACION EN VIP CADA VEZ QUE ENTRE',
  HASTA datetime NOT NULL DEFAULT '0000-00-00 00:00:00'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='ALMACENA LOS ID QUE IRAN AL VIP MULTIPLE';

lp2008_votos;
CREATE TABLE lp2008_votos (
  VOTO_ID int(11) NOT NULL,
  ID bigint(20) NOT NULL DEFAULT '0',
  VALOR int(11) NOT NULL DEFAULT '0',
  USUARIO varchar(100) NOT NULL,
  PLATAFORMA enum('PC','MO') NOT NULL DEFAULT 'PC',
  FECHA datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

lp2008_youtube;
CREATE TABLE lp2008_youtube (
  ID smallint(6) NOT NULL,
  USUARIO_ID mediumint(9) NOT NULL,
  CATEGORIA_ID tinyint(4) NOT NULL,
  TITULO varchar(60) NOT NULL,
  URLVIDEO varchar(60) NOT NULL,
  FECHA datetime NOT NULL,
  ESTATUS enum('A','I','R') NOT NULL DEFAULT 'A'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='ALMACENA LOS VIDEOS DE YOUTUBE';

lp2022_articulos;
CREATE TABLE lp2022_articulos (
  ID mediumint(9) NOT NULL,
  USUARIO_ID mediumint(9) NOT NULL DEFAULT '0',
  FECHA datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  EXPIRA datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  PUBLICADO enum('M','P') NOT NULL DEFAULT 'P' COMMENT 'M - MOVIL, P - PC',
  TIPO enum('C','V','S','B','A','T','M','E') NOT NULL DEFAULT 'V',
  PLAN enum('P','O','L','T','D','I') NOT NULL DEFAULT 'P' COMMENT 'TIPO DE PLAN DEL USUARIO',
  USUPLAN enum('PB','OP1','OP2','LPE','LP','LP+','TIE','DEA','INM') NOT NULL DEFAULT 'PB',
  PROVINCIA smallint(6) NOT NULL COMMENT 'LISTA POR PROVINCIAS',
  MUNICIPIO smallint(6) NOT NULL,
  LISTA enum('R','L') NOT NULL DEFAULT 'L' COMMENT 'L - NUEVOS, R - RENOVADOS',
  CATEGORIA_ID smallint(6) NOT NULL DEFAULT '1',
  SUBCATEGORIA_ID smallint(6) NOT NULL DEFAULT '1',
  ESTATUS enum('A','R','I','F','T','P','RO','RU','V','PA','RT') NOT NULL DEFAULT 'A' COMMENT 'RO: retira operador, RU: retira usuario, V Marcado vendido, PA-Pendiente aprobacion, RT - retirado temporal',
  CANTIDAD int(11) NOT NULL DEFAULT '1',
  PRECIO decimal(12,2) NOT NULL DEFAULT '0.00',
  ENVIO decimal(9,2) NOT NULL DEFAULT '0.00' COMMENT 'MONTO DE ENVIO',
  BONO enum('S','N') NOT NULL DEFAULT 'N' COMMENT 'MARCA SI EL ARTICULO TIENE BONO O NO',
  BN_FORMA enum('P','V') NOT NULL DEFAULT 'P',
  BN_VALOR decimal(15,2) NOT NULL DEFAULT '0.00',
  BN_HASTA date NOT NULL DEFAULT '0000-00-00',
  FORMAPAGO enum('P','G','T','N') NOT NULL DEFAULT 'N',
  MONEDA enum('R','U','E') NOT NULL DEFAULT 'R',
  ARTICULO varchar(70) NOT NULL DEFAULT '',
  REFERENCIA varchar(50) DEFAULT NULL,
  URLVIDEO varchar(120) NOT NULL DEFAULT '',
  OPCIONAL enum('N','R','FL') NOT NULL DEFAULT 'N',
  RESALTADO enum('N','R','FL') NOT NULL DEFAULT 'N' COMMENT 'RESALTA PUBLICACION',
  OPCHASTA datetime DEFAULT '0000-00-00 00:00:00',
  RESHASTA datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT 'FECHA CADUCA RESALTADO',
  APTABLOQUE enum('S','N') NOT NULL DEFAULT 'S' COMMENT 'APTA PARA BLOQUE VIP, AO, TIV, DEA, INM',
  PUBLICIDAD enum('S','N') NOT NULL DEFAULT 'N' COMMENT 'USADO PARA PUBLICIDAD ADWORDS',
  LINKAPLAN enum('S','N') NOT NULL DEFAULT 'N' COMMENT 'ENVIA PUBLICACION A PLAN O NO',
  FUERAPLAN enum('S','N') NOT NULL DEFAULT 'N' COMMENT 'PUBLICACIONES FUERA DEL PLAN',
  CONDICION enum('1','2','3','4','5') NOT NULL DEFAULT '1',
  FOTOS varchar(150) DEFAULT NULL,
  FOTOEXTERNA enum('S','N') NOT NULL DEFAULT 'N',
  URLFOTOEXT varchar(150) DEFAULT NULL,
  ROTAFOTO enum('N','S') NOT NULL DEFAULT 'N',
  VISITAS smallint(6) NOT NULL DEFAULT '0',
  VISITADO timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  ACUMULADAS smallint(6) NOT NULL DEFAULT '0' COMMENT 'VISITAS ACUMULADAS',
  ELIMINADO datetime DEFAULT NULL COMMENT 'FECHA ELIMINADO POR EL USUARIO',
  MOTIVOELI tinyint(4) DEFAULT NULL COMMENT 'MOTIVO ELIMIANDO POR EL USUARIO',
  IPADDRESS varchar(25) NOT NULL DEFAULT ''
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='ALMACENA LOS ARTICULOS DE USUARIOS REGISTRADOS';

temp_provincias;
CREATE TABLE temp_provincias (
  PROVINCIA tinyint(4) NOT NULL,
  CUANTOS smallint(6) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

vots;
CREATE TABLE vots (
  id bigint(20) NOT NULL DEFAULT '0',
  val int(11) NOT NULL DEFAULT '0',
  usuario varchar(100) NOT NULL,
  fecha datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

vots_acciondegracias;
CREATE TABLE vots_acciondegracias (
  id bigint(20) NOT NULL DEFAULT '0',
  val int(11) NOT NULL DEFAULT '0',
  fecha timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

vots_bailarinaspelota;
CREATE TABLE vots_bailarinaspelota (
  id bigint(20) NOT NULL DEFAULT '0',
  val int(11) NOT NULL DEFAULT '0',
  fecha timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

vots_bakery;
CREATE TABLE vots_bakery (
  id bigint(20) NOT NULL DEFAULT '0',
  val int(11) NOT NULL DEFAULT '0',
  fecha timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

vots_carry;
CREATE TABLE vots_carry (
  id bigint(20) NOT NULL DEFAULT '0',
  val int(11) NOT NULL DEFAULT '0',
  fecha timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

vots_conocestpago;
CREATE TABLE vots_conocestpago (
  id bigint(20) NOT NULL DEFAULT '0',
  val int(11) NOT NULL DEFAULT '0',
  fecha timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

vots_depot;
CREATE TABLE vots_depot (
  id bigint(20) NOT NULL DEFAULT '0',
  val int(11) NOT NULL DEFAULT '0',
  fecha timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

vots_grill;
CREATE TABLE vots_grill (
  id bigint(20) NOT NULL DEFAULT '0',
  val int(11) NOT NULL DEFAULT '0',
  fecha timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

vots_halloween;
CREATE TABLE vots_halloween (
  id bigint(20) NOT NULL DEFAULT '0',
  val int(11) NOT NULL DEFAULT '0',
  fecha timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

vots_lounge;
CREATE TABLE vots_lounge (
  id bigint(20) NOT NULL DEFAULT '0',
  val int(11) NOT NULL DEFAULT '0',
  fecha timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

vots_mall;
CREATE TABLE vots_mall (
  id bigint(20) NOT NULL DEFAULT '0',
  val int(11) NOT NULL DEFAULT '0',
  fecha timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

vots_nails;
CREATE TABLE vots_nails (
  id bigint(20) NOT NULL DEFAULT '0',
  val int(11) NOT NULL DEFAULT '0',
  fecha timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

vots_old091216;
CREATE TABLE vots_old091216 (
  id bigint(20) NOT NULL DEFAULT '0',
  val int(11) NOT NULL DEFAULT '0',
  fecha timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

vots_pines;
CREATE TABLE vots_pines (
  id bigint(20) NOT NULL DEFAULT '0',
  val int(11) NOT NULL DEFAULT '0',
  fecha timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

vots_promotinglp;
CREATE TABLE vots_promotinglp (
  id bigint(20) NOT NULL DEFAULT '0',
  val int(11) NOT NULL DEFAULT '0',
  fecha timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

vots_steak;
CREATE TABLE vots_steak (
  id bigint(20) NOT NULL DEFAULT '0',
  val int(11) NOT NULL DEFAULT '0',
  fecha timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

vots_tpagotienes;
CREATE TABLE vots_tpagotienes (
  id bigint(20) NOT NULL DEFAULT '0',
  val int(11) NOT NULL DEFAULT '0',
  fecha timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

vot_loundry;
CREATE TABLE vot_loundry (
  id bigint(20) NOT NULL DEFAULT '0',
  val int(11) NOT NULL DEFAULT '0',
  fecha timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


ALTER TABLE articles
  ADD PRIMARY KEY (id),
  ADD KEY product (product);

ALTER TABLE articles_old091216
  ADD PRIMARY KEY (id),
  ADD KEY product (product);

ALTER TABLE l2008_metatags
  ADD PRIMARY KEY (ARTICULO_ID);

ALTER TABLE lp2008_adicionales
  ADD PRIMARY KEY (ID),
  ADD KEY TIPO (TIPO);

ALTER TABLE lp2008_adicxarti
  ADD PRIMARY KEY (ARTICULO_ID,ADICIONAL_ID);

ALTER TABLE lp2008_anclarpub
  ADD PRIMARY KEY (ARTICULO_ID);

ALTER TABLE lp2008_artcoords
  ADD PRIMARY KEY (ARTICULO_ID);

ALTER TABLE lp2008_articulos
  ADD PRIMARY KEY (ID),
  ADD KEY CATEGORIA_ID (CATEGORIA_ID),
  ADD KEY SUBCATEGORIA_ID (SUBCATEGORIA_ID),
  ADD KEY TIPO (TIPO),
  ADD KEY BONO (BONO),
  ADD KEY USUARIO_ID (USUARIO_ID),
  ADD KEY LISTA (LISTA),
  ADD KEY ESTATUS (ESTATUS),
  ADD KEY PROVINCIA (PROVINCIA),
  ADD KEY APTABLOQUE (APTABLOQUE),
  ADD KEY USUPLAN (USUPLAN);
ALTER TABLE lp2008_articulos ADD FULLTEXT KEY I_ART_DESC (ARTICULO);

ALTER TABLE lp2008_arttemp
  ADD PRIMARY KEY (ID),
  ADD KEY ARTICULO (ARTICULO);

ALTER TABLE lp2008_autocompleta
  ADD PRIMARY KEY (ID);

ALTER TABLE lp2008_braices
  ADD PRIMARY KEY (ARTICULO_ID),
  ADD KEY HABITACIONES (HABITACIONES),
  ADD KEY PARQUEO (PARQUEOS);

ALTER TABLE lp2008_busquedas
  ADD UNIQUE KEY STR (STR),
  ADD KEY TIPO (TIPO),
  ADD KEY CUANTOS (CUANTOS);

ALTER TABLE lp2008_buzon
  ADD PRIMARY KEY (ID),
  ADD KEY PARA (PARA),
  ADD KEY DESDE (DE);

ALTER TABLE lp2008_cambioregistro
  ADD PRIMARY KEY (ID),
  ADD KEY USUARIO_ID (USUARIO_ID);

ALTER TABLE lp2008_categorias
  ADD PRIMARY KEY (ID),
  ADD UNIQUE KEY CATEGORIA (CATEGORIA);

ALTER TABLE lp2008_celulares
  ADD PRIMARY KEY (ARTICULO_ID);

ALTER TABLE lp2008_cemarca
  ADD PRIMARY KEY (ID);
ALTER TABLE lp2008_cemarca ADD FULLTEXT KEY MARCA (MARCA);

ALTER TABLE lp2008_cemodelo
  ADD PRIMARY KEY (ID);
ALTER TABLE lp2008_cemodelo ADD FULLTEXT KEY MODELO (MODELO);

ALTER TABLE lp2008_comentarticulos
  ADD PRIMARY KEY (ID),
  ADD KEY ARTICULO_ID (ARTICULO_ID);

ALTER TABLE lp2008_complementos
  ADD PRIMARY KEY (ARTICULO_ID),
  ADD KEY ESTATUS (ESTATUS),
  ADD KEY TIPOCOMP (TIPOCOMP);

ALTER TABLE lp2008_comusu
  ADD PRIMARY KEY (ID);

ALTER TABLE lp2008_cupones
  ADD PRIMARY KEY (CUPON);

ALTER TABLE lp2008_descripcion
  ADD PRIMARY KEY (ARTICULO_ID);
ALTER TABLE lp2008_descripcion ADD FULLTEXT KEY DESCRIPCION (DESCRIPCION);

ALTER TABLE lp2008_desctemp
  ADD PRIMARY KEY (ARTICULO_ID);

ALTER TABLE lp2008_descuentos
  ADD PRIMARY KEY (ARTICULO_ID);

ALTER TABLE lp2008_ealternos
  ADD PRIMARY KEY (USUARIO_ID);

ALTER TABLE lp2008_eliart
  ADD PRIMARY KEY (ID);

ALTER TABLE lp2008_encuestas
  ADD PRIMARY KEY (ID),
  ADD KEY product (PREGUNTA);

ALTER TABLE lp2008_enlpatr
  ADD PRIMARY KEY (ID),
  ADD KEY SECCION (SECCION),
  ADD KEY USUARIO_ID (USUARIO_ID),
  ADD KEY TIPO (TIPO);

ALTER TABLE lp2008_excedidos
  ADD PRIMARY KEY (USUARIO_ID);

ALTER TABLE lp2008_expreso
  ADD PRIMARY KEY (ID),
  ADD UNIQUE KEY USUARIO_ID (USUARIO_ID,ARTICULO_ID),
  ADD KEY UID (UID);

ALTER TABLE lp2008_extensiones
  ADD PRIMARY KEY (ID),
  ADD UNIQUE KEY USUARIO_ID (USUARIO_ID,FECHA,PROCESADO,ESTATUS);

ALTER TABLE lp2008_faq
  ADD PRIMARY KEY (ID),
  ADD UNIQUE KEY TOPICO (TOPICO);

ALTER TABLE lp2008_favoritas
  ADD PRIMARY KEY (ID),
  ADD UNIQUE KEY FAVORITO (USUARIO_ID,ARTICULO_ID);

ALTER TABLE lp2008_financieras
  ADD PRIMARY KEY (ID),
  ADD UNIQUE KEY EMAIL (EMAIL);

ALTER TABLE lp2008_finantipo
  ADD PRIMARY KEY (FINANCIERA_ID,TIPO);

ALTER TABLE lp2008_impresiones
  ADD UNIQUE KEY SECCION (SECCION,CATEGORIA_ID,FECHA);

ALTER TABLE lp2008_ip2c
  ADD PRIMARY KEY (id),
  ADD KEY begin_ip_num (begin_ip_num,end_ip_num);

ALTER TABLE lp2008_linkaplan
  ADD PRIMARY KEY (ID),
  ADD KEY ARTICULO_ID (ARTICULO_ID),
  ADD KEY HASTA (HASTA);

ALTER TABLE lp2008_listanegra
  ADD PRIMARY KEY (ID),
  ADD UNIQUE KEY VALOR (VALOR);

ALTER TABLE lp2008_log_acciones
  ADD PRIMARY KEY (ID);

ALTER TABLE lp2008_log_buscar
  ADD PRIMARY KEY (ID),
  ADD UNIQUE KEY STR (STR,USUARIO),
  ADD KEY TIPOB (TIPOB);

ALTER TABLE lp2008_log_click
  ADD PRIMARY KEY (ID);

ALTER TABLE lp2008_log_emailactual
  ADD PRIMARY KEY (ID),
  ADD KEY USUARIO_ID (USUARIO_ID);

ALTER TABLE lp2008_log_envmsg
  ADD PRIMARY KEY (ID),
  ADD KEY USUARIO_ID (USUARIO_ID);

ALTER TABLE lp2008_log_logins
  ADD PRIMARY KEY (ID),
  ADD KEY USUARIO_ID (USUARIO_ID),
  ADD KEY USUARIO (USUARIO);

ALTER TABLE lp2008_log_notifica
  ADD PRIMARY KEY (ID),
  ADD KEY USUARIO_ID (USUARIO_ID);

ALTER TABLE lp2008_log_palabras
  ADD PRIMARY KEY (ID);

ALTER TABLE lp2008_log_pines
  ADD PRIMARY KEY (ID);

ALTER TABLE lp2008_log_prestamos
  ADD UNIQUE KEY PRESTAMO_ID (PRESTAMO_ID,FINANCIERA_ID),
  ADD UNIQUE KEY PRESTAMO_ID_2 (PRESTAMO_ID,FINANCIERA_ID);

ALTER TABLE lp2008_log_pubusu
  ADD PRIMARY KEY (USUARIO_ID);

ALTER TABLE lp2008_lpbonos
  ADD PRIMARY KEY (ID),
  ADD UNIQUE KEY NUMERO (NUMERO),
  ADD UNIQUE KEY SESSION (SESSION);

ALTER TABLE lp2008_lppuntos
  ADD PRIMARY KEY (ID);

ALTER TABLE lp2008_mapxusu
  ADD PRIMARY KEY (USUARIO_ID,ARTICULO_ID);

ALTER TABLE lp2008_marcas
  ADD PRIMARY KEY (ID);

ALTER TABLE lp2008_mensajeria
  ADD PRIMARY KEY (ID),
  ADD UNIQUE KEY PARA (PARA,EMAIL,ARTICULO_ID);

ALTER TABLE lp2008_mensajes
  ADD PRIMARY KEY (ID);

ALTER TABLE lp2008_modelos
  ADD PRIMARY KEY (ID);

ALTER TABLE lp2008_msgarticulo
  ADD PRIMARY KEY (ID);

ALTER TABLE lp2008_msgcintillo
  ADD PRIMARY KEY (ID);

ALTER TABLE lp2008_municipios
  ADD PRIMARY KEY (ID),
  ADD KEY PROVINCIA_ID (PROVINCIA_ID);

ALTER TABLE lp2008_nologin
  ADD PRIMARY KEY (ID),
  ADD KEY USUARIO_ID (USUARIO_ID);

ALTER TABLE lp2008_notelefono
  ADD PRIMARY KEY (ID),
  ADD UNIQUE KEY TELEFONO (TELEFONO);

ALTER TABLE lp2008_opcionales
  ADD PRIMARY KEY (ID),
  ADD KEY ARTICULO_ID (ARTICULO_ID),
  ADD KEY TIPO (TIPO),
  ADD KEY ESTATUS (ESTATUS);

ALTER TABLE lp2008_palabras
  ADD UNIQUE KEY PALABRA (PALABRA);

ALTER TABLE lp2008_parametros
  ADD PRIMARY KEY (PARAMETRO);

ALTER TABLE lp2008_paramsmvc
  ADD PRIMARY KEY (PARAMETRO);

ALTER TABLE lp2008_pclaves
  ADD PRIMARY KEY (CATEGORIA_ID);
ALTER TABLE lp2008_pclaves ADD FULLTEXT KEY PCLAVES (PCLAVES);

ALTER TABLE lp2008_penalidades
  ADD PRIMARY KEY (ID),
  ADD UNIQUE KEY USUARIO_ID_2 (USUARIO_ID,HASTA),
  ADD KEY USUARIO_ID (USUARIO_ID);

ALTER TABLE lp2008_planenlista
  ADD PRIMARY KEY (ID);

ALTER TABLE lp2008_planes
  ADD PRIMARY KEY (USUARIO_ID);

ALTER TABLE lp2008_planesinfo
  ADD UNIQUE KEY USUARIO_ID (USUARIO_ID),
  ADD KEY HORARIO (HORARIO),
  ADD KEY TIPO (TIPO);
ALTER TABLE lp2008_planesinfo ADD FULLTEXT KEY NOMBRE_2 (NOMBRE);

ALTER TABLE lp2008_porprv
  ADD PRIMARY KEY (PROVINCIA_ID);

ALTER TABLE lp2008_prestamos
  ADD PRIMARY KEY (ID),
  ADD KEY EMAIL (EMAIL);

ALTER TABLE lp2008_provincias
  ADD PRIMARY KEY (ID),
  ADD KEY PROVINCIA (PROVINCIA);

ALTER TABLE lp2008_publicados
  ADD PRIMARY KEY (FECHA);

ALTER TABLE lp2008_publimite
  ADD PRIMARY KEY (ID),
  ADD KEY USUARIO_ID (USUARIO_ID);

ALTER TABLE lp2008_recientes
  ADD PRIMARY KEY (ARTICULO_ID,USUARIO),
  ADD KEY USUARIO (USUARIO);

ALTER TABLE lp2008_recurrentes
  ADD PRIMARY KEY (USUARIO_ID);

ALTER TABLE lp2008_referidos
  ADD PRIMARY KEY (ID),
  ADD UNIQUE KEY REFERIDO (REFERIDO);

ALTER TABLE lp2008_referidosold
  ADD PRIMARY KEY (ID);

ALTER TABLE lp2008_renomultiples
  ADD PRIMARY KEY (USUARIO_ID);

ALTER TABLE lp2008_renovaarticulo
  ADD PRIMARY KEY (ID);

ALTER TABLE lp2008_renovaciones
  ADD PRIMARY KEY (USUARIO_ID);

ALTER TABLE lp2008_repuemarca
  ADD PRIMARY KEY (REPUESTO_ID,MARCA);

ALTER TABLE lp2008_repuestos
  ADD PRIMARY KEY (ID),
  ADD UNIQUE KEY EMAIL (EMAIL);

ALTER TABLE lp2008_sectores
  ADD PRIMARY KEY (ID),
  ADD UNIQUE KEY PROVINCIA_ID (PROVINCIA_ID,SECTOR),
  ADD KEY MUNICIPIO_ID (MUNICIPIO_ID);
ALTER TABLE lp2008_sectores ADD FULLTEXT KEY SECTOR (SECTOR);

ALTER TABLE lp2008_sectoresn
  ADD PRIMARY KEY (ID),
  ADD UNIQUE KEY PROVINCIA_ID (PROVINCIA_ID,SECTOR),
  ADD KEY MUNICIPIO_ID (MUNICIPIO_ID);
ALTER TABLE lp2008_sectoresn ADD FULLTEXT KEY SECTOR (SECTOR);

ALTER TABLE lp2008_servicios
  ADD PRIMARY KEY (ID),
  ADD KEY SECTOR (SECTOR),
  ADD KEY PROVINCIA (PROVINCIA);
ALTER TABLE lp2008_servicios ADD FULLTEXT KEY NOMBRE (NOMBRE);
ALTER TABLE lp2008_servicios ADD FULLTEXT KEY SERVICIO (SERVICIO);
ALTER TABLE lp2008_servicios ADD FULLTEXT KEY SERVICIO_2 (SERVICIO);

ALTER TABLE lp2008_servicioscat
  ADD PRIMARY KEY (ID);

ALTER TABLE lp2008_sitemapindex
  ADD PRIMARY KEY (ID);

ALTER TABLE lp2008_solpiezas
  ADD PRIMARY KEY (ID);

ALTER TABLE lp2008_subcategorias
  ADD PRIMARY KEY (ID),
  ADD UNIQUE KEY CATEGORIA_ID (CATEGORIA_ID,SUBCATEGORIA);
ALTER TABLE lp2008_subcategorias ADD FULLTEXT KEY SUBCATEGORIA (SUBCATEGORIA);

ALTER TABLE lp2008_subplan
  ADD PRIMARY KEY (USUARIO_ID,SUBCATEGORIA_ID);

ALTER TABLE lp2008_subtienda
  ADD PRIMARY KEY (USUARIO_ID,SUBCATEGORIA_ID);

ALTER TABLE lp2008_sugiere
  ADD PRIMARY KEY (ARTICULO);
ALTER TABLE lp2008_sugiere ADD FULLTEXT KEY ARTICULO (ARTICULO);

ALTER TABLE lp2008_tempcuentas
  ADD PRIMARY KEY (TELEFONO);

ALTER TABLE lp2008_tiendas
  ADD UNIQUE KEY NOMBRE (NOMBRE),
  ADD UNIQUE KEY USUARIO_ID (USUARIO_ID);
ALTER TABLE lp2008_tiendas ADD FULLTEXT KEY NOMBRE_2 (NOMBRE);

ALTER TABLE lp2008_transacciones
  ADD PRIMARY KEY (ID),
  ADD KEY USUARIO_ID (USUARIO_ID),
  ADD KEY TIPO (FORMAPAGO);

ALTER TABLE lp2008_usuarios
  ADD PRIMARY KEY (ID),
  ADD UNIQUE KEY USUARIO (USUARIO),
  ADD UNIQUE KEY EMAIL (EMAIL),
  ADD KEY PROVINCIA (PROVINCIA),
  ADD KEY SECTOR (SECTOR),
  ADD KEY PAIS (PAIS),
  ADD KEY FBUSUARIO (FBUSUARIO),
  ADD KEY TWUSUARIO (TWUSUARIO),
  ADD KEY USUPLANN (USUPLANN);

ALTER TABLE lp2008_usubusca
  ADD PRIMARY KEY (ID),
  ADD KEY USUARIO (USUARIO);

ALTER TABLE lp2008_usuproc
  ADD PRIMARY KEY (ID),
  ADD UNIQUE KEY USUARIO_ID (USUARIO_ID,TIPO);

ALTER TABLE lp2008_usupromo
  ADD PRIMARY KEY (USUARIO_ID,PROMO);

ALTER TABLE lp2008_usutemp
  ADD PRIMARY KEY (ID),
  ADD UNIQUE KEY EMAIL (EMAIL),
  ADD UNIQUE KEY USUARIO (USUARIO);

ALTER TABLE lp2008_usuvisto
  ADD PRIMARY KEY (USUARIO_ID);

ALTER TABLE lp2008_vehiculos
  ADD PRIMARY KEY (ARTICULO_ID),
  ADD KEY MARCA (MARCAVE),
  ADD KEY MODELO (MODELO),
  ADD KEY ANIO (ANIO),
  ADD KEY COMBUSTIBLE (COMBUSTIBLE),
  ADD KEY TRANSMISION (TRANSMISION);

ALTER TABLE lp2008_vehmarca
  ADD PRIMARY KEY (ID);
ALTER TABLE lp2008_vehmarca ADD FULLTEXT KEY MARCA (MARCA);

ALTER TABLE lp2008_vehmodelo
  ADD PRIMARY KEY (ID);
ALTER TABLE lp2008_vehmodelo ADD FULLTEXT KEY MODELO (MODELO);

ALTER TABLE lp2008_vipmultiple
  ADD PRIMARY KEY (ID),
  ADD KEY ARTICULO_ID (ARTICULO_ID),
  ADD KEY TIPO (HASTA),
  ADD KEY SIGUIENTE (SIGUIENTE),
  ADD KEY ORDEN (ORDEN);

ALTER TABLE lp2008_votos
  ADD PRIMARY KEY (VOTO_ID),
  ADD KEY id (ID);

ALTER TABLE lp2008_youtube
  ADD PRIMARY KEY (ID),
  ADD UNIQUE KEY URLVIDEO (URLVIDEO);
ALTER TABLE lp2008_youtube ADD FULLTEXT KEY TITULO (TITULO);

ALTER TABLE lp2022_articulos
  ADD PRIMARY KEY (ID),
  ADD KEY CATEGORIA_ID (CATEGORIA_ID),
  ADD KEY SUBCATEGORIA_ID (SUBCATEGORIA_ID),
  ADD KEY TIPO (TIPO),
  ADD KEY BONO (BONO),
  ADD KEY USUARIO_ID (USUARIO_ID),
  ADD KEY LISTA (LISTA),
  ADD KEY ESTATUS (ESTATUS),
  ADD KEY PROVINCIA (PROVINCIA),
  ADD KEY APTABLOQUE (APTABLOQUE),
  ADD KEY USUPLAN (USUPLAN);
ALTER TABLE lp2022_articulos ADD FULLTEXT KEY I_ART_DESC (ARTICULO);

ALTER TABLE temp_provincias
  ADD PRIMARY KEY (PROVINCIA);

ALTER TABLE vots
  ADD KEY id (id);

ALTER TABLE vots_acciondegracias
  ADD KEY id (id);

ALTER TABLE vots_bailarinaspelota
  ADD KEY id (id);

ALTER TABLE vots_bakery
  ADD KEY id (id);

ALTER TABLE vots_carry
  ADD KEY id (id);

ALTER TABLE vots_conocestpago
  ADD KEY id (id);

ALTER TABLE vots_depot
  ADD KEY id (id);

ALTER TABLE vots_grill
  ADD KEY id (id);

ALTER TABLE vots_halloween
  ADD KEY id (id);

ALTER TABLE vots_lounge
  ADD KEY id (id);

ALTER TABLE vots_mall
  ADD KEY id (id);

ALTER TABLE vots_nails
  ADD KEY id (id);

ALTER TABLE vots_old091216
  ADD KEY id (id);

ALTER TABLE vots_pines
  ADD KEY id (id);

ALTER TABLE vots_promotinglp
  ADD KEY id (id);

ALTER TABLE vots_steak
  ADD KEY id (id);

ALTER TABLE vots_tpagotienes
  ADD KEY id (id);

ALTER TABLE vot_loundry
  ADD KEY id (id);


ALTER TABLE articles
  MODIFY id bigint(20) NOT NULL AUTO_INCREMENT;

ALTER TABLE articles_old091216
  MODIFY id bigint(20) NOT NULL AUTO_INCREMENT;

ALTER TABLE lp2008_adicionales
  MODIFY ID mediumint(9) NOT NULL AUTO_INCREMENT;

ALTER TABLE lp2008_articulos
  MODIFY ID mediumint(9) NOT NULL AUTO_INCREMENT;

ALTER TABLE lp2008_arttemp
  MODIFY ID int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE lp2008_autocompleta
  MODIFY ID int(11) NOT NULL AUTO_INCREMENT COMMENT 'ID DEL REGISTRO';

ALTER TABLE lp2008_buzon
  MODIFY ID mediumint(9) NOT NULL AUTO_INCREMENT;

ALTER TABLE lp2008_cambioregistro
  MODIFY ID mediumint(9) NOT NULL AUTO_INCREMENT;

ALTER TABLE lp2008_cemarca
  MODIFY ID tinyint(4) NOT NULL AUTO_INCREMENT;

ALTER TABLE lp2008_cemodelo
  MODIFY ID smallint(5) NOT NULL AUTO_INCREMENT;

ALTER TABLE lp2008_comentarticulos
  MODIFY ID bigint(20) NOT NULL AUTO_INCREMENT;

ALTER TABLE lp2008_comusu
  MODIFY ID mediumint(9) NOT NULL AUTO_INCREMENT;

ALTER TABLE lp2008_eliart
  MODIFY ID mediumint(9) NOT NULL AUTO_INCREMENT;

ALTER TABLE lp2008_encuestas
  MODIFY ID bigint(20) NOT NULL AUTO_INCREMENT;

ALTER TABLE lp2008_enlpatr
  MODIFY ID mediumint(5) NOT NULL AUTO_INCREMENT COMMENT 'ID que identifica el enlace patrocinado';

ALTER TABLE lp2008_expreso
  MODIFY ID int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE lp2008_extensiones
  MODIFY ID mediumint(9) NOT NULL AUTO_INCREMENT;

ALTER TABLE lp2008_faq
  MODIFY ID smallint(6) NOT NULL AUTO_INCREMENT;

ALTER TABLE lp2008_favoritas
  MODIFY ID mediumint(9) NOT NULL AUTO_INCREMENT;

ALTER TABLE lp2008_financieras
  MODIFY ID smallint(6) NOT NULL AUTO_INCREMENT;

ALTER TABLE lp2008_ip2c
  MODIFY id int(10) UNSIGNED NOT NULL AUTO_INCREMENT;

ALTER TABLE lp2008_linkaplan
  MODIFY ID smallint(6) NOT NULL AUTO_INCREMENT;

ALTER TABLE lp2008_log_acciones
  MODIFY ID mediumint(9) NOT NULL AUTO_INCREMENT;

ALTER TABLE lp2008_log_buscar
  MODIFY ID int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE lp2008_log_click
  MODIFY ID int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE lp2008_log_emailactual
  MODIFY ID mediumint(9) NOT NULL AUTO_INCREMENT;

ALTER TABLE lp2008_log_envmsg
  MODIFY ID mediumint(9) NOT NULL AUTO_INCREMENT;

ALTER TABLE lp2008_log_logins
  MODIFY ID bigint(20) NOT NULL AUTO_INCREMENT;

ALTER TABLE lp2008_log_notifica
  MODIFY ID smallint(6) NOT NULL AUTO_INCREMENT;

ALTER TABLE lp2008_log_palabras
  MODIFY ID int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE lp2008_log_pines
  MODIFY ID int(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'id del registro';

ALTER TABLE lp2008_lpbonos
  MODIFY ID mediumint(9) NOT NULL AUTO_INCREMENT;

ALTER TABLE lp2008_lppuntos
  MODIFY ID mediumint(9) NOT NULL AUTO_INCREMENT;

ALTER TABLE lp2008_marcas
  MODIFY ID smallint(6) NOT NULL AUTO_INCREMENT;

ALTER TABLE lp2008_mensajeria
  MODIFY ID mediumint(9) NOT NULL AUTO_INCREMENT;

ALTER TABLE lp2008_mensajes
  MODIFY ID smallint(6) NOT NULL AUTO_INCREMENT;

ALTER TABLE lp2008_modelos
  MODIFY ID smallint(6) NOT NULL AUTO_INCREMENT;

ALTER TABLE lp2008_msgarticulo
  MODIFY ID int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE lp2008_msgcintillo
  MODIFY ID smallint(6) NOT NULL AUTO_INCREMENT;

ALTER TABLE lp2008_municipios
  MODIFY ID int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE lp2008_nologin
  MODIFY ID smallint(6) NOT NULL AUTO_INCREMENT;

ALTER TABLE lp2008_notelefono
  MODIFY ID int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE lp2008_opcionales
  MODIFY ID mediumint(9) NOT NULL AUTO_INCREMENT;

ALTER TABLE lp2008_penalidades
  MODIFY ID smallint(6) NOT NULL AUTO_INCREMENT;

ALTER TABLE lp2008_planenlista
  MODIFY ID int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE lp2008_porprv
  MODIFY PROVINCIA_ID smallint(6) NOT NULL AUTO_INCREMENT;

ALTER TABLE lp2008_prestamos
  MODIFY ID mediumint(10) NOT NULL AUTO_INCREMENT;

ALTER TABLE lp2008_publimite
  MODIFY ID mediumint(9) NOT NULL AUTO_INCREMENT;

ALTER TABLE lp2008_referidos
  MODIFY ID int(6) NOT NULL AUTO_INCREMENT;

ALTER TABLE lp2008_referidosold
  MODIFY ID smallint(6) NOT NULL AUTO_INCREMENT;

ALTER TABLE lp2008_renovaarticulo
  MODIFY ID bigint(9) NOT NULL AUTO_INCREMENT;

ALTER TABLE lp2008_repuestos
  MODIFY ID smallint(6) NOT NULL AUTO_INCREMENT;

ALTER TABLE lp2008_sectores
  MODIFY ID smallint(6) NOT NULL AUTO_INCREMENT;

ALTER TABLE lp2008_sectoresn
  MODIFY ID smallint(6) NOT NULL AUTO_INCREMENT;

ALTER TABLE lp2008_servicios
  MODIFY ID mediumint(9) NOT NULL AUTO_INCREMENT;

ALTER TABLE lp2008_servicioscat
  MODIFY ID smallint(6) NOT NULL AUTO_INCREMENT;

ALTER TABLE lp2008_solpiezas
  MODIFY ID mediumint(10) NOT NULL AUTO_INCREMENT;

ALTER TABLE lp2008_subcategorias
  MODIFY ID smallint(6) NOT NULL AUTO_INCREMENT;

ALTER TABLE lp2008_transacciones
  MODIFY ID smallint(6) NOT NULL AUTO_INCREMENT;

ALTER TABLE lp2008_usuarios
  MODIFY ID mediumint(9) NOT NULL AUTO_INCREMENT;

ALTER TABLE lp2008_usubusca
  MODIFY ID smallint(6) NOT NULL AUTO_INCREMENT;

ALTER TABLE lp2008_usuproc
  MODIFY ID tinyint(4) NOT NULL AUTO_INCREMENT;

ALTER TABLE lp2008_usutemp
  MODIFY ID smallint(6) NOT NULL AUTO_INCREMENT;

ALTER TABLE lp2008_vehmarca
  MODIFY ID smallint(7) NOT NULL AUTO_INCREMENT;

ALTER TABLE lp2008_vehmodelo
  MODIFY ID smallint(7) NOT NULL AUTO_INCREMENT;

ALTER TABLE lp2008_vipmultiple
  MODIFY ID mediumint(9) NOT NULL AUTO_INCREMENT;

ALTER TABLE lp2008_votos
  MODIFY VOTO_ID int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE lp2008_youtube
  MODIFY ID smallint(6) NOT NULL AUTO_INCREMENT;

ALTER TABLE lp2022_articulos
  MODIFY ID mediumint(9) NOT NULL AUTO_INCREMENT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;

